import * as z from 'zod';

// Helper function to create skill fields schema
const createSkillFields = (index: number) => ({
  [`wUse_Skill_Time_${index}`]: z.number().nullable(),
  [`use_Skill_Tblidx_${index}`]: z.number().nullable(),
  [`byUse_Skill_Basis_${index}`]: z.number().nullable(),
  [`wUse_Skill_LP_${index}`]: z.number().nullable(),
});

// Create an array of indices from 0 to 9 for skills
const skillIndices = Array.from({ length: 10 }, (_, i) => i);

// Generate all skill fields
const skillFields = skillIndices.reduce((acc, index) => ({
  ...acc,
  ...createSkillFields(index),
}), {});

// Main schema definition
export const npcSchema = z.object({
  id: z.string().optional(),
  table_id: z.string().nullable(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
  tblidx: z.number().nullable(),
  bValidity_Able: z.coerce.boolean().nullable().transform(val => val ? 1 : 0),
  Name: z.number().nullable(),
  wszNameText: z.string().nullable().transform(e => e === null ? "" : e),
  szModel: z.string().nullable().transform(e => e === null ? "" : e),
  byLevel: z.number().nullable(),
  byGrade: z.number().nullable(),
  dwAi_Bit_Flag: z.number().nullable(),
  wLP_Regeneration: z.number().nullable(),
  wEP_Regeneration: z.number().nullable(),
  byAttack_Animation_Quantity: z.number().nullable(),
  byBattle_Attribute: z.number().nullable(),
  wBasic_Physical_Offence: z.number().nullable(),
  wBasic_Energy_Offence: z.number().nullable(),
  fWalk_Speed_Origin: z.number().nullable(),
  fWalk_Speed: z.number().nullable(),
  fRun_Speed_Origin: z.number().nullable(),
  fRun_Speed: z.number().nullable(),
  fRadius_X: z.number().nullable(),
  fRadius_Z: z.number().nullable(),
  wSight_Range: z.number().nullable(),
  wScan_Range: z.number().nullable(),
  byVisible_Sight_Range: z.number().nullable(),
  szCamera_Bone_Name: z.string().nullable().transform(e => e === null ? "" : e),
  wAttackCoolTime: z.number().nullable(),
  fFly_Height: z.number().nullable(),
  szNameText: z.string().nullable().transform(e => e === null ? "" : e),
  bSpawn_Animation: z.coerce.boolean().nullable().transform(val => val ? 1 : 0),
  dwDialogGroup: z.number().nullable(),
  szILLust: z.string().nullable().transform(e => e === null ? "" : e),
  dwAllianceIdx: z.number().nullable(),
  wAggroMaxCount: z.number().nullable(),
  dwNpcAttributeFlag: z.number().nullable(),
  wStomachacheDefence: z.number().nullable(),
  wPoisonDefence: z.number().nullable(),
  wBleedDefence: z.number().nullable(),
  wBurnDefence: z.number().nullable(),
  dwBasic_LP: z.number().nullable(),
  wBasic_EP: z.number().nullable(),
  wBasic_Physical_Defence: z.number().nullable(),
  wBasic_Energy_Defence: z.number().nullable(),
  wBasicStr: z.number().nullable(),
  wBasicCon: z.number().nullable(),
  wBasicFoc: z.number().nullable(),
  wBasicDex: z.number().nullable(),
  wBasicSol: z.number().nullable(),
  wBasicEng: z.number().nullable(),
  fScale: z.number().nullable(),
  wAttack_Speed_Rate: z.number().nullable(),
  byAttack_Type: z.number().nullable(),
  fAttack_Range: z.number().nullable(),
  wAttack_Rate: z.number().nullable(),
  wDodge_Rate: z.number().nullable(),
  wBlock_Rate: z.number().nullable(),
  wCurse_Success_Rate: z.number().nullable(),
  wCurse_Tolerance_Rate: z.number().nullable(),
  fRadius: z.number().nullable(),
  wBasic_Aggro_Point: z.number().nullable(),
  byNpcType: z.number().nullable(),
  byJob: z.number().nullable(),
  dwFunc_Bit_Flag: z.number().nullable(),
  Dialog_Script_Index: z.number().nullable(),
  statusTransformTblidx: z.number().nullable(),
  contentsTblidx: z.number().nullable(),
  wUnknown: z.number().nullable(),
  dwUnknown2: z.number().nullable(),
  dwUnknown3: z.number().nullable(),
  ...skillFields,
  amerchant_Tblidx_0: z.number().nullable(),
  amerchant_Tblidx_1: z.number().nullable(),
  amerchant_Tblidx_2: z.number().nullable(),
  amerchant_Tblidx_3: z.number().nullable(),
  amerchant_Tblidx_4: z.number().nullable(),
  amerchant_Tblidx_5: z.number().nullable(),
  amerchant_Tblidx_6: z.number().nullable(),
  amerchant_Tblidx_7: z.number().nullable(),
  amerchant_Tblidx_8: z.number().nullable(),
  amerchant_Tblidx_9: z.number().nullable(),
});

// Column definitions for the table
export const columns = [
  { key: 'tblidx', label: 'TBLIDX', type: 'number' as const, validation: npcSchema.shape.tblidx },
  { key: 'bValidity_Able', label: 'Valid', type: 'boolean' as const, validation: npcSchema.shape.bValidity_Able },
  { key: 'Name', label: 'Name ID', type: 'number' as const, validation: npcSchema.shape.Name },
  { key: 'wszNameText', label: 'Name', type: 'text' as const, validation: npcSchema.shape.wszNameText },
  { key: 'szModel', label: 'Model', type: 'text' as const, validation: npcSchema.shape.szModel },
  { key: 'byLevel', label: 'Level', type: 'number' as const, validation: npcSchema.shape.byLevel },
  { key: 'byGrade', label: 'Grade', type: 'number' as const, validation: npcSchema.shape.byGrade },
  { key: 'dwAi_Bit_Flag', label: 'AI Bit Flag', type: 'number' as const, validation: npcSchema.shape.dwAi_Bit_Flag },
  { key: 'wLP_Regeneration', label: 'LP Regen', type: 'number' as const, validation: npcSchema.shape.wLP_Regeneration },
  { key: 'wEP_Regeneration', label: 'EP Regen', type: 'number' as const, validation: npcSchema.shape.wEP_Regeneration },
  { key: 'byAttack_Animation_Quantity', label: 'Attack Animation Quantity', type: 'number' as const, validation: npcSchema.shape.byAttack_Animation_Quantity },
  { key: 'byBattle_Attribute', label: 'Battle Attribute', type: 'number' as const, validation: npcSchema.shape.byBattle_Attribute },
  { key: 'wBasic_Physical_Offence', label: 'Physical Attack', type: 'number' as const, validation: npcSchema.shape.wBasic_Physical_Offence },
  { key: 'wBasic_Energy_Offence', label: 'Energy Attack', type: 'number' as const, validation: npcSchema.shape.wBasic_Energy_Offence },
  { key: 'fWalk_Speed_Origin', label: 'Base Walk Speed', type: 'number' as const, validation: npcSchema.shape.fWalk_Speed_Origin },
  { key: 'fWalk_Speed', label: 'Walk Speed', type: 'number' as const, validation: npcSchema.shape.fWalk_Speed },
  { key: 'fRun_Speed_Origin', label: 'Base Run Speed', type: 'number' as const, validation: npcSchema.shape.fRun_Speed_Origin },
  { key: 'fRun_Speed', label: 'Run Speed', type: 'number' as const, validation: npcSchema.shape.fRun_Speed },
  { key: 'fRadius_X', label: 'Radius X', type: 'number' as const, validation: npcSchema.shape.fRadius_X },
  { key: 'fRadius_Z', label: 'Radius Z', type: 'number' as const, validation: npcSchema.shape.fRadius_Z },
  { key: 'wSight_Range', label: 'Sight Range', type: 'number' as const, validation: npcSchema.shape.wSight_Range },
  { key: 'wScan_Range', label: 'Scan Range', type: 'number' as const, validation: npcSchema.shape.wScan_Range },
  { key: 'byVisible_Sight_Range', label: 'Visible Sight Range', type: 'number' as const, validation: npcSchema.shape.byVisible_Sight_Range },
  { key: 'szCamera_Bone_Name', label: 'Camera Bone', type: 'text' as const, validation: npcSchema.shape.szCamera_Bone_Name },
  { key: 'wAttackCoolTime', label: 'Attack Cooldown', type: 'number' as const, validation: npcSchema.shape.wAttackCoolTime },
  { key: 'fFly_Height', label: 'Fly Height', type: 'number' as const, validation: npcSchema.shape.fFly_Height },
  { key: 'szNameText', label: 'Display Name', type: 'text' as const, validation: npcSchema.shape.szNameText },
  { key: 'bSpawn_Animation', label: 'Spawn Animation', type: 'boolean' as const, validation: npcSchema.shape.bSpawn_Animation },
  { key: 'dwDialogGroup', label: 'Dialog Group', type: 'number' as const, validation: npcSchema.shape.dwDialogGroup },
  { key: 'szILLust', label: 'Illustration', type: 'text' as const, validation: npcSchema.shape.szILLust },
  { key: 'dwAllianceIdx', label: 'Alliance Index', type: 'number' as const, validation: npcSchema.shape.dwAllianceIdx },
  { key: 'wAggroMaxCount', label: 'Max Aggro Count', type: 'number' as const, validation: npcSchema.shape.wAggroMaxCount },
  { key: 'dwNpcAttributeFlag', label: 'NPC Attribute Flag', type: 'number' as const, validation: npcSchema.shape.dwNpcAttributeFlag },
  { key: 'wStomachacheDefence', label: 'Stomachache Defense', type: 'number' as const, validation: npcSchema.shape.wStomachacheDefence },
  { key: 'wPoisonDefence', label: 'Poison Defense', type: 'number' as const, validation: npcSchema.shape.wPoisonDefence },
  { key: 'wBleedDefence', label: 'Bleed Defense', type: 'number' as const, validation: npcSchema.shape.wBleedDefence },
  { key: 'wBurnDefence', label: 'Burn Defense', type: 'number' as const, validation: npcSchema.shape.wBurnDefence },
  { key: 'dwBasic_LP', label: 'Base LP', type: 'number' as const, validation: npcSchema.shape.dwBasic_LP },
  { key: 'wBasic_EP', label: 'Base EP', type: 'number' as const, validation: npcSchema.shape.wBasic_EP },
  { key: 'wBasic_Physical_Defence', label: 'Physical Defense', type: 'number' as const, validation: npcSchema.shape.wBasic_Physical_Defence },
  { key: 'wBasic_Energy_Defence', label: 'Energy Defense', type: 'number' as const, validation: npcSchema.shape.wBasic_Energy_Defence },
  { key: 'wBasicStr', label: 'STR', type: 'number' as const, validation: npcSchema.shape.wBasicStr },
  { key: 'wBasicCon', label: 'CON', type: 'number' as const, validation: npcSchema.shape.wBasicCon },
  { key: 'wBasicFoc', label: 'FOC', type: 'number' as const, validation: npcSchema.shape.wBasicFoc },
  { key: 'wBasicDex', label: 'DEX', type: 'number' as const, validation: npcSchema.shape.wBasicDex },
  { key: 'wBasicSol', label: 'SOL', type: 'number' as const, validation: npcSchema.shape.wBasicSol },
  { key: 'wBasicEng', label: 'ENG', type: 'number' as const, validation: npcSchema.shape.wBasicEng },
  { key: 'fScale', label: 'Scale', type: 'number' as const, validation: npcSchema.shape.fScale },
  { key: 'wAttack_Speed_Rate', label: 'Attack Speed Rate', type: 'number' as const, validation: npcSchema.shape.wAttack_Speed_Rate },
  { key: 'byAttack_Type', label: 'Attack Type', type: 'number' as const, validation: npcSchema.shape.byAttack_Type },
  { key: 'fAttack_Range', label: 'Attack Range', type: 'number' as const, validation: npcSchema.shape.fAttack_Range },
  { key: 'wAttack_Rate', label: 'Attack Rate', type: 'number' as const, validation: npcSchema.shape.wAttack_Rate },
  { key: 'wDodge_Rate', label: 'Dodge Rate', type: 'number' as const, validation: npcSchema.shape.wDodge_Rate },
  { key: 'wBlock_Rate', label: 'Block Rate', type: 'number' as const, validation: npcSchema.shape.wBlock_Rate },
  { key: 'wCurse_Success_Rate', label: 'Curse Success Rate', type: 'number' as const, validation: npcSchema.shape.wCurse_Success_Rate },
  { key: 'wCurse_Tolerance_Rate', label: 'Curse Tolerance Rate', type: 'number' as const, validation: npcSchema.shape.wCurse_Tolerance_Rate },
  { key: 'fRadius', label: 'Radius', type: 'number' as const, validation: npcSchema.shape.fRadius },
  { key: 'wBasic_Aggro_Point', label: 'Base Aggro Point', type: 'number' as const, validation: npcSchema.shape.wBasic_Aggro_Point },
  { key: 'byNpcType', label: 'NPC Type', type: 'number' as const, validation: npcSchema.shape.byNpcType },
  { key: 'byJob', label: 'Job', type: 'number' as const, validation: npcSchema.shape.byJob },
  { key: 'dwFunc_Bit_Flag', label: 'Function Bit Flag', type: 'number' as const, validation: npcSchema.shape.dwFunc_Bit_Flag },
  { key: 'Dialog_Script_Index', label: 'Dialog Script Index', type: 'number' as const, validation: npcSchema.shape.Dialog_Script_Index },
  { key: 'statusTransformTblidx', label: 'Status Transform Index', type: 'number' as const, validation: npcSchema.shape.statusTransformTblidx },
  { key: 'contentsTblidx', label: 'Contents Index', type: 'number' as const, validation: npcSchema.shape.contentsTblidx },
  ...skillIndices.flatMap(index => [
    { key: `wUse_Skill_Time_${index}`, label: `Skill ${index} Time`, type: 'number' as const, validation: npcSchema.shape[`wUse_Skill_Time_${index}` as keyof typeof npcSchema.shape] },
    { key: `use_Skill_Tblidx_${index}`, label: `Skill ${index} Index`, type: 'number' as const, validation: npcSchema.shape[`use_Skill_Tblidx_${index}` as keyof typeof npcSchema.shape] },
    { key: `byUse_Skill_Basis_${index}`, label: `Skill ${index} Basis`, type: 'number' as const, validation: npcSchema.shape[`byUse_Skill_Basis_${index}` as keyof typeof npcSchema.shape] },
    { key: `wUse_Skill_LP_${index}`, label: `Skill ${index} LP`, type: 'number' as const, validation: npcSchema.shape[`wUse_Skill_LP_${index}` as keyof typeof npcSchema.shape] }
  ]),
  { key: 'amerchant_Tblidx_0', label: 'Merchant Index 0', type: 'number' as const, validation: npcSchema.shape.amerchant_Tblidx_0 },
  { key: 'amerchant_Tblidx_1', label: 'Merchant Index 1', type: 'number' as const, validation: npcSchema.shape.amerchant_Tblidx_1 },
  { key: 'amerchant_Tblidx_2', label: 'Merchant Index 2', type: 'number' as const, validation: npcSchema.shape.amerchant_Tblidx_2 },
  { key: 'amerchant_Tblidx_3', label: 'Merchant Index 3', type: 'number' as const, validation: npcSchema.shape.amerchant_Tblidx_3 },
  { key: 'amerchant_Tblidx_4', label: 'Merchant Index 4', type: 'number' as const, validation: npcSchema.shape.amerchant_Tblidx_4 },
  { key: 'amerchant_Tblidx_5', label: 'Merchant Index 5', type: 'number' as const, validation: npcSchema.shape.amerchant_Tblidx_5 },
  { key: 'amerchant_Tblidx_6', label: 'Merchant Index 6', type: 'number' as const, validation: npcSchema.shape.amerchant_Tblidx_6 },
  { key: 'amerchant_Tblidx_7', label: 'Merchant Index 7', type: 'number' as const, validation: npcSchema.shape.amerchant_Tblidx_7 },
  { key: 'amerchant_Tblidx_8', label: 'Merchant Index 8', type: 'number' as const, validation: npcSchema.shape.amerchant_Tblidx_8 },
  { key: 'amerchant_Tblidx_9', label: 'Merchant Index 9', type: 'number' as const, validation: npcSchema.shape.amerchant_Tblidx_9 }
];

export type NpcFormData = z.infer<typeof npcSchema>;
