/* eslint-disable @typescript-eslint/no-explicit-any */
import * as z from 'zod';

export const tmqTableSchema = z.object({
  table_id: z.string().uuid(),
  tblidx: z.coerce.number().min(0, 'Must be a positive number').max(9999999999, 'Cannot exceed 10 digits'),
  byTimeQuestType: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  byDifficultyFlag: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  dwStartTime: z.coerce.number().min(0, 'Must be a positive number'),
  startCharacterDirection: z.coerce.number().min(0, 'Must be a positive number'),
  startObjectIndex: z.coerce.number().min(0, 'Must be a positive number'),
  startTriggerId: z.coerce.number().min(0, 'Must be a positive number'),
  arriveCharacterDirection: z.coerce.number().min(0, 'Must be a positive number'),
  arriveObjectIndex: z.coerce.number().min(0, 'Must be a positive number'),
  arriveTriggerId: z.coerce.number().min(0, 'Must be a positive number'),
  leaveCharacterDirection: z.coerce.number().min(0, 'Must be a positive number'),
  leaveObjectIndex: z.coerce.number().min(0, 'Must be a positive number'),
  leaveTriggerId: z.coerce.number().min(0, 'Must be a positive number'),
  dayRecordMailTblidx: z.coerce.number().min(0, 'Must be a positive number'),
  bestRecordMailTblidx: z.coerce.number().min(0, 'Must be a positive number'),
  byResetTime: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  wszPrologueDirection: z.string().nullable().transform(e => e === null ? "" : e),
  openCine: z.coerce.number().min(0, 'Must be a positive number'),
  Note: z.coerce.number().min(0, 'Must be a positive number'),
  wszStageBgm1: z.string().nullable().transform(e => e === null ? "" : e),
  wszStageBgm2: z.string().nullable().transform(e => e === null ? "" : e),
  wszLastBgm: z.string().nullable().transform(e => e === null ? "" : e),
  abyStartTriggerDirectionState_0: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  abyStartTriggerDirectionState_1: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  abyStartTriggerDirectionState_2: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  abyStartTriggerDirectionState_3: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  abyStartTriggerDirectionState_4: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  abyStartTriggerDirectionState_5: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  abyStartTriggerDirectionState_6: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  abyStartTriggerDirectionState_7: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  abyStartTriggerDirectionState_8: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  abyStartTriggerDirectionState_9: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  sTimeQuestDataset_0_nameTblidx: z.coerce.number().min(0, 'Must be a positive number'),
  sTimeQuestDataset_0_questStringTblidx: z.coerce.number().min(0, 'Must be a positive number'),
  sTimeQuestDataset_0_worldTblidx: z.coerce.number().min(0, 'Must be a positive number'),
  sTimeQuestDataset_0_scriptTblidx: z.coerce.number().min(0, 'Must be a positive number'),
  sTimeQuestDataset_0_byMinMemberCount: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  sTimeQuestDataset_0_byMaxMemberCount: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  sTimeQuestDataset_0_byMinMemberLevel: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  sTimeQuestDataset_0_byMaxMemberLevel: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  sTimeQuestDataset_0_dwLimitTime: z.coerce.number().min(0, 'Must be a positive number'),
  sTimeQuestDataset_0_dwNeedZenny: z.coerce.number().min(0, 'Must be a positive number'),
  sTimeQuestDataset_0_needItemTblidx: z.coerce.number().min(0, 'Must be a positive number'),
  sTimeQuestDataset_0_byNeedLimitCount: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  sTimeQuestDataset_0_byWorldCount: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  sTimeQuestDataset_0_dayRecordRewardTblidx: z.coerce.number().min(0, 'Must be a positive number'),
  sTimeQuestDataset_0_bestRecordRewardTblidx: z.coerce.number().min(0, 'Must be a positive number'),
  sTimeQuestDataset_1_nameTblidx: z.coerce.number().min(0, 'Must be a positive number'),
  sTimeQuestDataset_1_questStringTblidx: z.coerce.number().min(0, 'Must be a positive number'),
  sTimeQuestDataset_1_worldTblidx: z.coerce.number().min(0, 'Must be a positive number'),
  sTimeQuestDataset_1_scriptTblidx: z.coerce.number().min(0, 'Must be a positive number'),
  sTimeQuestDataset_1_byMinMemberCount: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  sTimeQuestDataset_1_byMaxMemberCount: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  sTimeQuestDataset_1_byMinMemberLevel: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  sTimeQuestDataset_1_byMaxMemberLevel: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  sTimeQuestDataset_1_dwLimitTime: z.coerce.number().min(0, 'Must be a positive number'),
  sTimeQuestDataset_1_dwNeedZenny: z.coerce.number().min(0, 'Must be a positive number'),
  sTimeQuestDataset_1_needItemTblidx: z.coerce.number().min(0, 'Must be a positive number'),
  sTimeQuestDataset_1_byNeedLimitCount: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  sTimeQuestDataset_1_byWorldCount: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  sTimeQuestDataset_1_dayRecordRewardTblidx: z.coerce.number().min(0, 'Must be a positive number'),
  sTimeQuestDataset_1_bestRecordRewardTblidx: z.coerce.number().min(0, 'Must be a positive number'),
  sTimeQuestDataset_2_nameTblidx: z.coerce.number().min(0, 'Must be a positive number'),
  sTimeQuestDataset_2_questStringTblidx: z.coerce.number().min(0, 'Must be a positive number'),
  sTimeQuestDataset_2_worldTblidx: z.coerce.number().min(0, 'Must be a positive number'),
  sTimeQuestDataset_2_scriptTblidx: z.coerce.number().min(0, 'Must be a positive number'),
  sTimeQuestDataset_2_byMinMemberCount: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  sTimeQuestDataset_2_byMaxMemberCount: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  sTimeQuestDataset_2_byMinMemberLevel: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  sTimeQuestDataset_2_byMaxMemberLevel: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  sTimeQuestDataset_2_dwLimitTime: z.coerce.number().min(0, 'Must be a positive number'),
  sTimeQuestDataset_2_dwNeedZenny: z.coerce.number().min(0, 'Must be a positive number'),
  sTimeQuestDataset_2_needItemTblidx: z.coerce.number().min(0, 'Must be a positive number'),
  sTimeQuestDataset_2_byNeedLimitCount: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  sTimeQuestDataset_2_byWorldCount: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  sTimeQuestDataset_2_dayRecordRewardTblidx: z.coerce.number().min(0, 'Must be a positive number'),
  sTimeQuestDataset_2_bestRecordRewardTblidx: z.coerce.number().min(0, 'Must be a positive number'),
});

export type TmqTableFormData = z.infer<typeof tmqTableSchema>;

export interface TmqTableRow extends TmqTableFormData {
  id: string;
}

const startTriggerDirectionStateColumns = Array.from({ length: 10 }, (_, i) => ({
  key: `abyStartTriggerDirectionState_${i}` as const,
  label: `Start Trigger Direction State ${i}`,
  type: 'number' as const,
  validation: tmqTableSchema.shape[`abyStartTriggerDirectionState_${i}` as keyof typeof tmqTableSchema.shape] as any,
}));

// Helper function to generate time quest dataset columns
const generateTimeQuestDatasetColumns = (datasetIndex: number) => [
  { key: `sTimeQuestDataset_${datasetIndex}_nameTblidx` as const, label: `Dataset ${datasetIndex} Name Table ID`, type: 'number' as const, validation: tmqTableSchema.shape[`sTimeQuestDataset_${datasetIndex}_nameTblidx` as keyof typeof tmqTableSchema.shape] as any },
  { key: `sTimeQuestDataset_${datasetIndex}_questStringTblidx` as const, label: `Dataset ${datasetIndex} Quest String Table ID`, type: 'number' as const, validation: tmqTableSchema.shape[`sTimeQuestDataset_${datasetIndex}_questStringTblidx` as keyof typeof tmqTableSchema.shape] as any },
  { key: `sTimeQuestDataset_${datasetIndex}_worldTblidx` as const, label: `Dataset ${datasetIndex} World Table ID`, type: 'number' as const, validation: tmqTableSchema.shape[`sTimeQuestDataset_${datasetIndex}_worldTblidx` as keyof typeof tmqTableSchema.shape] as any },
  { key: `sTimeQuestDataset_${datasetIndex}_scriptTblidx` as const, label: `Dataset ${datasetIndex} Script Table ID`, type: 'number' as const, validation: tmqTableSchema.shape[`sTimeQuestDataset_${datasetIndex}_scriptTblidx` as keyof typeof tmqTableSchema.shape] as any },
  { key: `sTimeQuestDataset_${datasetIndex}_byMinMemberCount` as const, label: `Dataset ${datasetIndex} Min Member Count`, type: 'number' as const, validation: tmqTableSchema.shape[`sTimeQuestDataset_${datasetIndex}_byMinMemberCount` as keyof typeof tmqTableSchema.shape] as any },
  { key: `sTimeQuestDataset_${datasetIndex}_byMaxMemberCount` as const, label: `Dataset ${datasetIndex} Max Member Count`, type: 'number' as const, validation: tmqTableSchema.shape[`sTimeQuestDataset_${datasetIndex}_byMaxMemberCount` as keyof typeof tmqTableSchema.shape] as any },
  { key: `sTimeQuestDataset_${datasetIndex}_byMinMemberLevel` as const, label: `Dataset ${datasetIndex} Min Member Level`, type: 'number' as const, validation: tmqTableSchema.shape[`sTimeQuestDataset_${datasetIndex}_byMinMemberLevel` as keyof typeof tmqTableSchema.shape] as any },
  { key: `sTimeQuestDataset_${datasetIndex}_byMaxMemberLevel` as const, label: `Dataset ${datasetIndex} Max Member Level`, type: 'number' as const, validation: tmqTableSchema.shape[`sTimeQuestDataset_${datasetIndex}_byMaxMemberLevel` as keyof typeof tmqTableSchema.shape] as any },
  { key: `sTimeQuestDataset_${datasetIndex}_dwLimitTime` as const, label: `Dataset ${datasetIndex} Limit Time`, type: 'number' as const, validation: tmqTableSchema.shape[`sTimeQuestDataset_${datasetIndex}_dwLimitTime` as keyof typeof tmqTableSchema.shape] as any },
  { key: `sTimeQuestDataset_${datasetIndex}_dwNeedZenny` as const, label: `Dataset ${datasetIndex} Need Zenny`, type: 'number' as const, validation: tmqTableSchema.shape[`sTimeQuestDataset_${datasetIndex}_dwNeedZenny` as keyof typeof tmqTableSchema.shape] as any },
  { key: `sTimeQuestDataset_${datasetIndex}_needItemTblidx` as const, label: `Dataset ${datasetIndex} Need Item Table ID`, type: 'number' as const, validation: tmqTableSchema.shape[`sTimeQuestDataset_${datasetIndex}_needItemTblidx` as keyof typeof tmqTableSchema.shape] as any },
  { key: `sTimeQuestDataset_${datasetIndex}_byNeedLimitCount` as const, label: `Dataset ${datasetIndex} Need Limit Count`, type: 'number' as const, validation: tmqTableSchema.shape[`sTimeQuestDataset_${datasetIndex}_byNeedLimitCount` as keyof typeof tmqTableSchema.shape] as any },
  { key: `sTimeQuestDataset_${datasetIndex}_byWorldCount` as const, label: `Dataset ${datasetIndex} World Count`, type: 'number' as const, validation: tmqTableSchema.shape[`sTimeQuestDataset_${datasetIndex}_byWorldCount` as keyof typeof tmqTableSchema.shape] as any },
  { key: `sTimeQuestDataset_${datasetIndex}_dayRecordRewardTblidx` as const, label: `Dataset ${datasetIndex} Day Record Reward Table ID`, type: 'number' as const, validation: tmqTableSchema.shape[`sTimeQuestDataset_${datasetIndex}_dayRecordRewardTblidx` as keyof typeof tmqTableSchema.shape] as any },
  { key: `sTimeQuestDataset_${datasetIndex}_bestRecordRewardTblidx` as const, label: `Dataset ${datasetIndex} Best Record Reward Table ID`, type: 'number' as const, validation: tmqTableSchema.shape[`sTimeQuestDataset_${datasetIndex}_bestRecordRewardTblidx` as keyof typeof tmqTableSchema.shape] as any },
];

const timeQuestDatasetColumns = Array.from({ length: 3 }, (_, i) => generateTimeQuestDatasetColumns(i)).flat();

export const columns = [
  { key: 'tblidx', label: 'Table ID', type: 'number' as const, validation: tmqTableSchema.shape.tblidx },
  { key: 'byTimeQuestType', label: 'Time Quest Type', type: 'number' as const, validation: tmqTableSchema.shape.byTimeQuestType },
  { key: 'byDifficultyFlag', label: 'Difficulty Flag', type: 'number' as const, validation: tmqTableSchema.shape.byDifficultyFlag },
  { key: 'dwStartTime', label: 'Start Time', type: 'number' as const, validation: tmqTableSchema.shape.dwStartTime },
  { key: 'startCharacterDirection', label: 'Start Character Direction', type: 'number' as const, validation: tmqTableSchema.shape.startCharacterDirection },
  { key: 'startObjectIndex', label: 'Start Object Index', type: 'number' as const, validation: tmqTableSchema.shape.startObjectIndex },
  { key: 'startTriggerId', label: 'Start Trigger ID', type: 'number' as const, validation: tmqTableSchema.shape.startTriggerId },
  { key: 'arriveCharacterDirection', label: 'Arrive Character Direction', type: 'number' as const, validation: tmqTableSchema.shape.arriveCharacterDirection },
  { key: 'arriveObjectIndex', label: 'Arrive Object Index', type: 'number' as const, validation: tmqTableSchema.shape.arriveObjectIndex },
  { key: 'arriveTriggerId', label: 'Arrive Trigger ID', type: 'number' as const, validation: tmqTableSchema.shape.arriveTriggerId },
  { key: 'leaveCharacterDirection', label: 'Leave Character Direction', type: 'number' as const, validation: tmqTableSchema.shape.leaveCharacterDirection },
  { key: 'leaveObjectIndex', label: 'Leave Object Index', type: 'number' as const, validation: tmqTableSchema.shape.leaveObjectIndex },
  { key: 'leaveTriggerId', label: 'Leave Trigger ID', type: 'number' as const, validation: tmqTableSchema.shape.leaveTriggerId },
  { key: 'dayRecordMailTblidx', label: 'Day Record Mail Table ID', type: 'number' as const, validation: tmqTableSchema.shape.dayRecordMailTblidx },
  { key: 'bestRecordMailTblidx', label: 'Best Record Mail Table ID', type: 'number' as const, validation: tmqTableSchema.shape.bestRecordMailTblidx },
  { key: 'byResetTime', label: 'Reset Time', type: 'number' as const, validation: tmqTableSchema.shape.byResetTime },
  { key: 'wszPrologueDirection', label: 'Prologue Direction', type: 'text' as const, validation: tmqTableSchema.shape.wszPrologueDirection },
  { key: 'openCine', label: 'Open Cine', type: 'number' as const, validation: tmqTableSchema.shape.openCine },
  { key: 'Note', label: 'Note', type: 'number' as const, validation: tmqTableSchema.shape.Note },
  { key: 'wszStageBgm1', label: 'Stage BGM 1', type: 'text' as const, validation: tmqTableSchema.shape.wszStageBgm1 },
  { key: 'wszStageBgm2', label: 'Stage BGM 2', type: 'text' as const, validation: tmqTableSchema.shape.wszStageBgm2 },
  { key: 'wszLastBgm', label: 'Last BGM', type: 'text' as const, validation: tmqTableSchema.shape.wszLastBgm },
  ...startTriggerDirectionStateColumns,
  ...timeQuestDatasetColumns,
];

