import * as z from 'zod';

export const slotMachineSchema = z.object({
  table_id: z.string().uuid(),
  tblidx: z.coerce.number().min(0, 'Must be a positive number').max(9999999999, 'Cannot exceed 10 digits').nullable(),
  dwName: z.coerce.number().nullable(),
  wszNameText: z.string().nullable().transform(e => e === null ? "" : e),
  szFile_Name: z.string().nullable().transform(e => e === null ? "" : e),
  byCoin: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  bOnOff: z.coerce.boolean().nullable().transform(val => val ? 1 : 0),
  byType: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  wfirstWinCoin: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  aItemTblidx_0: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  byStack_0: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  wQuantity_0: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  aItemTblidx_1: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  byStack_1: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  wQuantity_1: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  aItemTblidx_2: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  byStack_2: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  wQuantity_2: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  aItemTblidx_3: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  byStack_3: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  wQuantity_3: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  aItemTblidx_4: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  byStack_4: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  wQuantity_4: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  aItemTblidx_5: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  byStack_5: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  wQuantity_5: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  aItemTblidx_6: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  byStack_6: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  wQuantity_6: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  aItemTblidx_7: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  byStack_7: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  wQuantity_7: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  aItemTblidx_8: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  byStack_8: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  wQuantity_8: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  aItemTblidx_9: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  byStack_9: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  wQuantity_9: z.coerce.number().min(0, 'Must be a positive number').nullable(),
});

export type SlotMachineFormData = z.infer<typeof slotMachineSchema>;

export const columns = [
  { key: 'tblidx', label: 'ID', type: 'number' as const, validation: slotMachineSchema.shape.tblidx },
  { key: 'dwName', label: 'Name', type: 'number' as const, validation: slotMachineSchema.shape.dwName },
  { key: 'wszNameText', label: 'Display Name', type: 'text' as const, validation: slotMachineSchema.shape.wszNameText },
  { key: 'szFile_Name', label: 'File Name', type: 'text' as const, validation: slotMachineSchema.shape.szFile_Name },
  { key: 'byCoin', label: 'Coin', type: 'number' as const, validation: slotMachineSchema.shape.byCoin },
  { key: 'bOnOff', label: 'On/Off', type: 'boolean' as const, validation: slotMachineSchema.shape.bOnOff },
  { key: 'byType', label: 'Type', type: 'number' as const, validation: slotMachineSchema.shape.byType },
  { key: 'wfirstWinCoin', label: 'First Win Coin', type: 'number' as const, validation: slotMachineSchema.shape.wfirstWinCoin },
  ...Array.from({ length: 10 }, (_, i) => [
    { key: `aItemTblidx_${i}`, label: `Item ${i + 1} ID`, type: 'number' as const, validation: slotMachineSchema.shape[`aItemTblidx_${i}` as keyof typeof slotMachineSchema.shape] },
    { key: `byStack_${i}`, label: `Item ${i + 1} Stack`, type: 'number' as const, validation: slotMachineSchema.shape[`byStack_${i}` as keyof typeof slotMachineSchema.shape] },
    { key: `wQuantity_${i}`, label: `Item ${i + 1} Quantity`, type: 'number' as const, validation: slotMachineSchema.shape[`wQuantity_${i}` as keyof typeof slotMachineSchema.shape] }
  ]).flat(),
];
