import * as z from 'zod';

export const slotMachineSchema = z.object({
  table_id: z.string().uuid(),
  tblidx: z.coerce.number().min(0, 'Must be a positive number').max(9999999999, 'Cannot exceed 10 digits').nullable(),
  dwname: z.string().nullable(),
  wsznametext: z.string().nullable(),
  szfile_name: z.string().nullable(),
  bycoin: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  bonoff: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  bytype: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  wfirstwincoin: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  aitemtblidx_0: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  bystack_0: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  wquantity_0: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  aitemtblidx_1: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  bystack_1: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  wquantity_1: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  aitemtblidx_2: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  bystack_2: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  wquantity_2: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  aitemtblidx_3: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  bystack_3: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  wquantity_3: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  aitemtblidx_4: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  bystack_4: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  wquantity_4: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  aitemtblidx_5: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  bystack_5: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  wquantity_5: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  aitemtblidx_6: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  bystack_6: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  wquantity_6: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  aitemtblidx_7: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  bystack_7: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  wquantity_7: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  aitemtblidx_8: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  bystack_8: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  wquantity_8: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  aitemtblidx_9: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  bystack_9: z.coerce.number().min(0, 'Must be a positive number').nullable(),
  wquantity_9: z.coerce.number().min(0, 'Must be a positive number').nullable(),
});

export type SlotMachineFormData = z.infer<typeof slotMachineSchema>;

export const columns = [
  { key: 'tblidx', label: 'ID', type: 'number' as const, validation: slotMachineSchema.shape.tblidx },
  { key: 'dwname', label: 'Name', type: 'text' as const, validation: slotMachineSchema.shape.dwname },
  { key: 'wsznametext', label: 'Display Name', type: 'text' as const, validation: slotMachineSchema.shape.wsznametext },
  { key: 'szfile_name', label: 'File Name', type: 'text' as const, validation: slotMachineSchema.shape.szfile_name },
  { key: 'bycoin', label: 'Coin', type: 'number' as const, validation: slotMachineSchema.shape.bycoin },
  { key: 'bonoff', label: 'On/Off', type: 'number' as const, validation: slotMachineSchema.shape.bonoff },
  { key: 'bytype', label: 'Type', type: 'number' as const, validation: slotMachineSchema.shape.bytype },
  { key: 'wfirstwincoin', label: 'First Win Coin', type: 'number' as const, validation: slotMachineSchema.shape.wfirstwincoin },
  ...Array.from({ length: 10 }, (_, i) => [
    { key: `aitemtblidx_${i}`, label: `Item ${i} ID`, type: 'number' as const, validation: slotMachineSchema.shape[`aitemtblidx_${i}` as keyof typeof slotMachineSchema.shape] },
    { key: `bystack_${i}`, label: `Item ${i} Stack`, type: 'number' as const, validation: slotMachineSchema.shape[`bystack_${i}` as keyof typeof slotMachineSchema.shape] },
    { key: `wquantity_${i}`, label: `Item ${i} Quantity`, type: 'number' as const, validation: slotMachineSchema.shape[`wquantity_${i}` as keyof typeof slotMachineSchema.shape] }
  ]).flat(),
]; 