import * as z from 'zod';

export const pcTableSchema = z.object({
  table_id: z.string().uuid(),
  tblidx: z.coerce.number().min(0, 'Must be a positive number').max(9999999999, 'Cannot exceed 10 digits'),
  dwBasic_LP: z.coerce.number().min(0, 'Must be a positive number'),
  wBasic_EP: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  wBasic_Physical_Defence: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  wBasic_Energy_Defence: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  wBasicStr: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  wBasicCon: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  wBasicFoc: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  wBasicDex: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  wBasicSol: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  wBasicEng: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  fScale: z.coerce.number(),
  wAttack_Speed_Rate: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  byAttack_Type: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  fAttack_Range: z.coerce.number(),
  wAttack_Rate: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  wDodge_Rate: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  wBlock_Rate: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  wCurse_Success_Rate: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  wCurse_Tolerance_Rate: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  fRadius: z.coerce.number(),
  wBasic_Aggro_Point: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  byRace: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  byGender: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  byClass: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  prior_Class_Tblidx: z.coerce.number().min(0, 'Must be a positive number'),
  dwClass_Bit_Flag: z.coerce.number().min(0, 'Must be a positive number'),
  szModel_Child: z.string().max(64, 'Cannot exceed 64 characters'),
  szModel_Adult: z.string().max(64, 'Cannot exceed 64 characters'),
  fChild_Run_Speed_Origin: z.coerce.number(),
  fChild_Run_Speed: z.coerce.number(),
  fAdult_Run_Speed_Origin: z.coerce.number(),
  fAdult_Run_Speed: z.coerce.number(),
  fChild_Fly_Speed_Origin: z.coerce.number(),
  fChild_Fly_Speed: z.coerce.number(),
  fAdult_Fly_Speed_Origin: z.coerce.number(),
  fAdult_Fly_Speed: z.coerce.number(),
  fChild_Dash_Speed_Origin: z.coerce.number(),
  fChild_Dash_Speed: z.coerce.number(),
  fAdult_Dash_Speed_Origin: z.coerce.number(),
  fAdult_Dash_Speed: z.coerce.number(),
  fChild_Accel_Speed_Origin: z.coerce.number(),
  fChild_Accel_Speed: z.coerce.number(),
  fAdult_Accel_Speed_Origin: z.coerce.number(),
  fAdult_Accel_Speed: z.coerce.number(),
  wBasic_RP: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  wBasic_Physical_Offence: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  wBasic_Energy_Offence: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  dwWeightLimit: z.coerce.number().min(0, 'Must be a positive number'),
  byLevel_Up_LP: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  byLevel_Up_EP: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  byLevel_Up_RP: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  byLevel_Up_Physical_Offence: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  byLevel_Up_Physical_Defence: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  byLevel_Up_Energy_Offence: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  byLevel_Up_Energy_Defence: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  fLevel_Up_Str: z.coerce.number(),
  fLevel_Up_Con: z.coerce.number(),
  fLevel_Up_Foc: z.coerce.number(),
  fLevel_Up_Dex: z.coerce.number(),
  fLevel_Up_Sol: z.coerce.number(),
  fLevel_Up_Eng: z.coerce.number(),
});

export type PcTableFormData = z.infer<typeof pcTableSchema>;

export interface PcTableRow extends PcTableFormData {
  id: string;
}

export const columns = [
  { key: 'tblidx', label: 'Table ID', type: 'number' as const, validation: pcTableSchema.shape.tblidx },
  { key: 'dwBasic_LP', label: 'Basic LP', type: 'number' as const, validation: pcTableSchema.shape.dwBasic_LP },
  { key: 'wBasic_EP', label: 'Basic EP', type: 'number' as const, validation: pcTableSchema.shape.wBasic_EP },
  { key: 'wBasic_Physical_Defence', label: 'Basic Physical Defence', type: 'number' as const, validation: pcTableSchema.shape.wBasic_Physical_Defence },
  { key: 'wBasic_Energy_Defence', label: 'Basic Energy Defence', type: 'number' as const, validation: pcTableSchema.shape.wBasic_Energy_Defence },
  { key: 'wBasicStr', label: 'Basic Str', type: 'number' as const, validation: pcTableSchema.shape.wBasicStr },
  { key: 'wBasicCon', label: 'Basic Con', type: 'number' as const, validation: pcTableSchema.shape.wBasicCon },
  { key: 'wBasicFoc', label: 'Basic Foc', type: 'number' as const, validation: pcTableSchema.shape.wBasicFoc },
  { key: 'wBasicDex', label: 'Basic Dex', type: 'number' as const, validation: pcTableSchema.shape.wBasicDex },
  { key: 'wBasicSol', label: 'Basic Sol', type: 'number' as const, validation: pcTableSchema.shape.wBasicSol },
  { key: 'wBasicEng', label: 'Basic Eng', type: 'number' as const, validation: pcTableSchema.shape.wBasicEng },
  { key: 'fScale', label: 'Scale', type: 'number' as const, validation: pcTableSchema.shape.fScale },
  { key: 'wAttack_Speed_Rate', label: 'Attack Speed Rate', type: 'number' as const, validation: pcTableSchema.shape.wAttack_Speed_Rate },
  { key: 'byAttack_Type', label: 'Attack Type', type: 'number' as const, validation: pcTableSchema.shape.byAttack_Type },
  { key: 'fAttack_Range', label: 'Attack Range', type: 'number' as const, validation: pcTableSchema.shape.fAttack_Range },
  { key: 'wAttack_Rate', label: 'Attack Rate', type: 'number' as const, validation: pcTableSchema.shape.wAttack_Rate },
  { key: 'wDodge_Rate', label: 'Dodge Rate', type: 'number' as const, validation: pcTableSchema.shape.wDodge_Rate },
  { key: 'wBlock_Rate', label: 'Block Rate', type: 'number' as const, validation: pcTableSchema.shape.wBlock_Rate },
  { key: 'wCurse_Success_Rate', label: 'Curse Success Rate', type: 'number' as const, validation: pcTableSchema.shape.wCurse_Success_Rate },
  { key: 'wCurse_Tolerance_Rate', label: 'Curse Tolerance Rate', type: 'number' as const, validation: pcTableSchema.shape.wCurse_Tolerance_Rate },
  { key: 'fRadius', label: 'Radius', type: 'number' as const, validation: pcTableSchema.shape.fRadius },
  { key: 'wBasic_Aggro_Point', label: 'Basic Aggro Point', type: 'number' as const, validation: pcTableSchema.shape.wBasic_Aggro_Point },
  { key: 'byRace', label: 'Race', type: 'number' as const, validation: pcTableSchema.shape.byRace },
  { key: 'byGender', label: 'Gender', type: 'number' as const, validation: pcTableSchema.shape.byGender },
  { key: 'byClass', label: 'Class', type: 'number' as const, validation: pcTableSchema.shape.byClass },
  { key: 'prior_Class_Tblidx', label: 'Prior Class Table ID', type: 'number' as const, validation: pcTableSchema.shape.prior_Class_Tblidx },
  { key: 'dwClass_Bit_Flag', label: 'Class Bit Flag', type: 'number' as const, validation: pcTableSchema.shape.dwClass_Bit_Flag },
  { key: 'szModel_Child', label: 'Model Child', type: 'text' as const, validation: pcTableSchema.shape.szModel_Child },
  { key: 'szModel_Adult', label: 'Model Adult', type: 'text' as const, validation: pcTableSchema.shape.szModel_Adult },
  { key: 'fChild_Run_Speed_Origin', label: 'Child Run Speed Origin', type: 'number' as const, validation: pcTableSchema.shape.fChild_Run_Speed_Origin },
  { key: 'fChild_Run_Speed', label: 'Child Run Speed', type: 'number' as const, validation: pcTableSchema.shape.fChild_Run_Speed },
  { key: 'fAdult_Run_Speed_Origin', label: 'Adult Run Speed Origin', type: 'number' as const, validation: pcTableSchema.shape.fAdult_Run_Speed_Origin },
  { key: 'fAdult_Run_Speed', label: 'Adult Run Speed', type: 'number' as const, validation: pcTableSchema.shape.fAdult_Run_Speed },
  { key: 'fChild_Fly_Speed_Origin', label: 'Child Fly Speed Origin', type: 'number' as const, validation: pcTableSchema.shape.fChild_Fly_Speed_Origin },
  { key: 'fChild_Fly_Speed', label: 'Child Fly Speed', type: 'number' as const, validation: pcTableSchema.shape.fChild_Fly_Speed },
  { key: 'fAdult_Fly_Speed_Origin', label: 'Adult Fly Speed Origin', type: 'number' as const, validation: pcTableSchema.shape.fAdult_Fly_Speed_Origin },
  { key: 'fAdult_Fly_Speed', label: 'Adult Fly Speed', type: 'number' as const, validation: pcTableSchema.shape.fAdult_Fly_Speed },
  { key: 'fChild_Dash_Speed_Origin', label: 'Child Dash Speed Origin', type: 'number' as const, validation: pcTableSchema.shape.fChild_Dash_Speed_Origin },
  { key: 'fChild_Dash_Speed', label: 'Child Dash Speed', type: 'number' as const, validation: pcTableSchema.shape.fChild_Dash_Speed },
  { key: 'fAdult_Dash_Speed_Origin', label: 'Adult Dash Speed Origin', type: 'number' as const, validation: pcTableSchema.shape.fAdult_Dash_Speed_Origin },
  { key: 'fAdult_Dash_Speed', label: 'Adult Dash Speed', type: 'number' as const, validation: pcTableSchema.shape.fAdult_Dash_Speed },
  { key: 'fChild_Accel_Speed_Origin', label: 'Child Accel Speed Origin', type: 'number' as const, validation: pcTableSchema.shape.fChild_Accel_Speed_Origin },
  { key: 'fChild_Accel_Speed', label: 'Child Accel Speed', type: 'number' as const, validation: pcTableSchema.shape.fChild_Accel_Speed },
  { key: 'fAdult_Accel_Speed_Origin', label: 'Adult Accel Speed Origin', type: 'number' as const, validation: pcTableSchema.shape.fAdult_Accel_Speed_Origin },
  { key: 'fAdult_Accel_Speed', label: 'Adult Accel Speed', type: 'number' as const, validation: pcTableSchema.shape.fAdult_Accel_Speed },
  { key: 'wBasic_RP', label: 'Basic RP', type: 'number' as const, validation: pcTableSchema.shape.wBasic_RP },
  { key: 'wBasic_Physical_Offence', label: 'Basic Physical Offence', type: 'number' as const, validation: pcTableSchema.shape.wBasic_Physical_Offence },
  { key: 'wBasic_Energy_Offence', label: 'Basic Energy Offence', type: 'number' as const, validation: pcTableSchema.shape.wBasic_Energy_Offence },
  { key: 'dwWeightLimit', label: 'Weight Limit', type: 'number' as const, validation: pcTableSchema.shape.dwWeightLimit },
  { key: 'byLevel_Up_LP', label: 'Level Up LP', type: 'number' as const, validation: pcTableSchema.shape.byLevel_Up_LP },
  { key: 'byLevel_Up_EP', label: 'Level Up EP', type: 'number' as const, validation: pcTableSchema.shape.byLevel_Up_EP },
  { key: 'byLevel_Up_RP', label: 'Level Up RP', type: 'number' as const, validation: pcTableSchema.shape.byLevel_Up_RP },
  { key: 'byLevel_Up_Physical_Offence', label: 'Level Up Physical Offence', type: 'number' as const, validation: pcTableSchema.shape.byLevel_Up_Physical_Offence },
  { key: 'byLevel_Up_Physical_Defence', label: 'Level Up Physical Defence', type: 'number' as const, validation: pcTableSchema.shape.byLevel_Up_Physical_Defence },
  { key: 'byLevel_Up_Energy_Offence', label: 'Level Up Energy Offence', type: 'number' as const, validation: pcTableSchema.shape.byLevel_Up_Energy_Offence },
  { key: 'byLevel_Up_Energy_Defence', label: 'Level Up Energy Defence', type: 'number' as const, validation: pcTableSchema.shape.byLevel_Up_Energy_Defence },
  { key: 'fLevel_Up_Str', label: 'Level Up Str', type: 'number' as const, validation: pcTableSchema.shape.fLevel_Up_Str },
  { key: 'fLevel_Up_Con', label: 'Level Up Con', type: 'number' as const, validation: pcTableSchema.shape.fLevel_Up_Con },
  { key: 'fLevel_Up_Foc', label: 'Level Up Foc', type: 'number' as const, validation: pcTableSchema.shape.fLevel_Up_Foc },
  { key: 'fLevel_Up_Dex', label: 'Level Up Dex', type: 'number' as const, validation: pcTableSchema.shape.fLevel_Up_Dex },
  { key: 'fLevel_Up_Sol', label: 'Level Up Sol', type: 'number' as const, validation: pcTableSchema.shape.fLevel_Up_Sol },
  { key: 'fLevel_Up_Eng', label: 'Level Up Eng', type: 'number' as const, validation: pcTableSchema.shape.fLevel_Up_Eng },
];

