import { z } from "zod";

export const hlsItemSchema = z.object({
  table_id: z.string().uuid(),
  tblidx: z.coerce.number().min(0, 'Must be a positive number').max(9999999999, 'Cannot exceed 10 digits').optional(),
  wszName: z.string().nullable().transform(e => e === null ? "" : e).optional(),
  wszCJIProductID: z.string().nullable().transform(e => e === null ? "" : e).optional(),
  szIcon_Name: z.string().nullable().transform(e => e === null ? "" : e).optional(),
  wHLSItemType: z.coerce.number().min(0, 'Must be a positive number').optional(),
  byHLSDurationType: z.coerce.number().min(0, 'Must be a positive number').optional(),
  dwHLSDurationTime: z.coerce.number().min(0, 'Must be a positive number').optional(),
  idxNameText: z.coerce.number().min(0, 'Must be a positive number').optional(),
  idxNoteText: z.coerce.number().min(0, 'Must be a positive number').optional(),
  itemTblidx: z.coerce.number().min(0, 'Must be a positive number').optional(),
  bOnSale: z.coerce.boolean().nullable().transform(val => val ? 1 : 0).optional(),
  bySellType: z.coerce.number().min(0, 'Must be a positive number').optional(),
  dwCash: z.coerce.number().min(0, 'Must be a positive number').optional(),
  byDiscount: z.coerce.number().min(0, 'Must be a positive number').optional(),
  byStackCount: z.coerce.number().min(0, 'Must be a positive number').optional(),
  wDisplayBitFlag: z.coerce.number().min(0, 'Must be a positive number').optional(),
  byQuickLink: z.coerce.number().min(0, 'Must be a positive number').optional(),
  dwPriority: z.coerce.number().min(0, 'Must be a positive number').optional(),
  byDisplayConsumeType: z.coerce.number().min(0, 'Must be a positive number').optional(),
  byYadratType: z.coerce.number().min(0, 'Must be a positive number').optional(),
  itemTblidx_0: z.coerce.number().min(0, 'Must be a positive number').optional(),
  byStackCount_0: z.coerce.number().min(0, 'Must be a positive number').optional(),
  itemTblidx_1: z.coerce.number().min(0, 'Must be a positive number').optional(),
  byStackCount_1: z.coerce.number().min(0, 'Must be a positive number').optional(),
  itemTblidx_2: z.coerce.number().min(0, 'Must be a positive number').optional(),
  byStackCount_2: z.coerce.number().min(0, 'Must be a positive number').optional(),
  itemTblidx_3: z.coerce.number().min(0, 'Must be a positive number').optional(),
  byStackCount_3: z.coerce.number().min(0, 'Must be a positive number').optional(),
  itemTblidx_4: z.coerce.number().min(0, 'Must be a positive number').optional(),
  byStackCount_4: z.coerce.number().min(0, 'Must be a positive number').optional(),
});

export type HlsItemFormData = z.infer<typeof hlsItemSchema>;

export const columns = [
  { key: 'tblidx', label: 'ID', type: 'number' as const, validation: hlsItemSchema.shape.tblidx },
  { key: 'wszName', label: 'Name', type: 'text' as const, validation: hlsItemSchema.shape.wszName },
  { key: 'wszCJIProductID', label: 'Product ID', type: 'text' as const, validation: hlsItemSchema.shape.wszCJIProductID },
  { key: 'szIcon_Name', label: 'Icon Name', type: 'text' as const, validation: hlsItemSchema.shape.szIcon_Name },
  { key: 'wHLSItemType', label: 'Item Type', type: 'number' as const, validation: hlsItemSchema.shape.wHLSItemType },
  { key: 'byHLSDurationType', label: 'Duration Type', type: 'number' as const, validation: hlsItemSchema.shape.byHLSDurationType },
  { key: 'dwHLSDurationTime', label: 'Duration Time', type: 'number' as const, validation: hlsItemSchema.shape.dwHLSDurationTime },
  { key: 'idxNameText', label: 'Name Text Index', type: 'number' as const, validation: hlsItemSchema.shape.idxNameText },
  { key: 'idxNoteText', label: 'Note Text Index', type: 'number' as const, validation: hlsItemSchema.shape.idxNoteText },
  { key: 'itemTblidx', label: 'Item ID', type: 'number' as const, validation: hlsItemSchema.shape.itemTblidx },
  { key: 'bOnSale', label: 'On Sale', type: 'boolean' as const, validation: hlsItemSchema.shape.bOnSale },
  { key: 'bySellType', label: 'Sell Type', type: 'number' as const, validation: hlsItemSchema.shape.bySellType },
  { key: 'dwCash', label: 'Cash', type: 'number' as const, validation: hlsItemSchema.shape.dwCash },
  { key: 'byDiscount', label: 'Discount', type: 'number' as const, validation: hlsItemSchema.shape.byDiscount },
  { key: 'byStackCount', label: 'Stack Count', type: 'number' as const, validation: hlsItemSchema.shape.byStackCount },
  { key: 'wDisplayBitFlag', label: 'Display Bit Flag', type: 'number' as const, validation: hlsItemSchema.shape.wDisplayBitFlag },
  { key: 'byQuickLink', label: 'Quick Link', type: 'number' as const, validation: hlsItemSchema.shape.byQuickLink },
  { key: 'dwPriority', label: 'Priority', type: 'number' as const, validation: hlsItemSchema.shape.dwPriority },
  { key: 'byDisplayConsumeType', label: 'Display Consume Type', type: 'number' as const, validation: hlsItemSchema.shape.byDisplayConsumeType },
  { key: 'byYadratType', label: 'Yadrat Type', type: 'number' as const, validation: hlsItemSchema.shape.byYadratType },
  ...Array.from({ length: 5 }, (_, i) => [
    { key: `itemTblidx_${i}`, label: `Item ${i + 1} ID`, type: 'number' as const, validation: hlsItemSchema.shape[`itemTblidx_${i}` as keyof typeof hlsItemSchema.shape] },
    { key: `byStackCount_${i}`, label: `Item ${i + 1} Stack`, type: 'number' as const, validation: hlsItemSchema.shape[`byStackCount_${i}` as keyof typeof hlsItemSchema.shape] }
  ]).flat(),
];
