import { z } from "zod";

export const hlsItemSchema = z.object({
  table_id: z.string().uuid(),
  tblidx: z.coerce.number().min(0, 'Must be a positive number').max(9999999999, 'Cannot exceed 10 digits').optional(),
  wszname: z.string().optional(),
  wszcjiproductid: z.string().optional(),
  szicon_name: z.string().optional(),
  whlsitemtype: z.coerce.number().min(0, 'Must be a positive number').optional(),
  byhlsdurationtype: z.coerce.number().min(0, 'Must be a positive number').optional(),
  dwhlsdurationtime: z.coerce.number().min(0, 'Must be a positive number').optional(),
  idxnametext: z.coerce.number().min(0, 'Must be a positive number').optional(),
  idxnotetext: z.coerce.number().min(0, 'Must be a positive number').optional(),
  itemtblidx: z.coerce.number().min(0, 'Must be a positive number').optional(),
  bonsale: z.coerce.number().min(0).max(1).optional(),
  byselltype: z.coerce.number().min(0, 'Must be a positive number').optional(),
  dwcash: z.coerce.number().min(0, 'Must be a positive number').optional(),
  bydiscount: z.coerce.number().min(0, 'Must be a positive number').optional(),
  bystackcount: z.coerce.number().min(0, 'Must be a positive number').optional(),
  wdisplaybitflag: z.coerce.number().min(0, 'Must be a positive number').optional(),
  byquicklink: z.coerce.number().min(0, 'Must be a positive number').optional(),
  dwpriority: z.coerce.number().min(0, 'Must be a positive number').optional(),
  bydisplayconsumetype: z.coerce.number().min(0, 'Must be a positive number').optional(),
  byyadrattype: z.coerce.number().min(0, 'Must be a positive number').optional(),
  itemtblidx_0: z.coerce.number().min(0, 'Must be a positive number').optional(),
  bystackcount_0: z.coerce.number().min(0, 'Must be a positive number').optional(),
  itemtblidx_1: z.coerce.number().min(0, 'Must be a positive number').optional(),
  bystackcount_1: z.coerce.number().min(0, 'Must be a positive number').optional(),
  itemtblidx_2: z.coerce.number().min(0, 'Must be a positive number').optional(),
  bystackcount_2: z.coerce.number().min(0, 'Must be a positive number').optional(),
  itemtblidx_3: z.coerce.number().min(0, 'Must be a positive number').optional(),
  bystackcount_3: z.coerce.number().min(0, 'Must be a positive number').optional(),
  itemtblidx_4: z.coerce.number().min(0, 'Must be a positive number').optional(),
  bystackcount_4: z.coerce.number().min(0, 'Must be a positive number').optional(),
}); 