import * as z from "zod";

export const useItemSchema = z.object({
  table_id: z.string().uuid().nullable(),
  tblidx: z.coerce.number().nullable(),
  byUse_Item_Active_Type: z.coerce.number().nullable(),
  byBuff_Group: z.coerce.number().nullable(),
  byBuffKeepType: z.coerce.number().nullable(),
  dwCool_Time_Bit_Flag: z.coerce.number().nullable(),
  wFunction_Bit_Flag: z.coerce.number().nullable(),
  dwUse_Restriction_Rule_Bit_Flag: z.coerce.number().nullable(),
  dwUse_Allow_Rule_Bit_Flag: z.coerce.number().nullable(),
  byAppoint_Target: z.coerce.number().nullable(),
  byApply_Target: z.coerce.number().nullable(),
  dwApply_Target_Index: z.coerce.number().nullable(),
  byApply_Target_Max: z.coerce.number().nullable(),
  byApply_Range: z.coerce.number().nullable(),
  byApply_Area_Size_1: z.coerce.number().nullable(),
  byApply_Area_Size_2: z.coerce.number().nullable(),
  wNeed_State_Bit_Flag: z.coerce.number().nullable(),
  dwRequire_LP: z.coerce.number().nullable(),
  wRequire_EP: z.coerce.number().nullable(),
  byRequire_RP_Ball: z.coerce.number().nullable(),
  fCasting_Time: z.coerce.number().nullable(),
  dwCastingTimeInMilliSecs: z.coerce.number().nullable(),
  dwCool_Time: z.coerce.number().nullable(),
  dwCoolTimeInMilliSecs: z.coerce.number().nullable(),
  dwKeep_Time: z.coerce.number().nullable(),
  dwKeepTimeInMilliSecs: z.coerce.number().nullable(),
  bKeep_Effect: z.coerce.boolean().nullable().transform(val => val ? 1 : 0),
  byUse_Range_Min: z.coerce.number().nullable(),
  fUse_Range_Min: z.coerce.number().nullable(),
  byUse_Range_Max: z.coerce.number().nullable(),
  fUse_Range_Max: z.coerce.number().nullable(),
  Use_Info_Text: z.coerce.number().nullable(),
  szCasting_Effect: z.string().nullable().transform(e => e === null ? "" : e),
  szAction_Effect: z.string().nullable().transform(e => e === null ? "" : e),
  wCasting_Animation_Start: z.coerce.number().nullable(),
  wCasting_Animation_Loop: z.coerce.number().nullable(),
  wAction_Animation_Index: z.coerce.number().nullable(),
  wAction_Loop_Animation_Index: z.coerce.number().nullable(),
  wAction_End_Animation_Index: z.coerce.number().nullable(),
  byCastingEffectPosition: z.coerce.number().nullable(),
  byActionEffectPosition: z.coerce.number().nullable(),
  useWorldTblidx: z.coerce.number().nullable(),
  fUseLoc_X: z.coerce.number().nullable(),
  fUseLoc_Z: z.coerce.number().nullable(),
  fUseLoc_Radius: z.coerce.number().nullable(),
  RequiredQuestID: z.coerce.number().nullable(),
  aSystem_Effect_0: z.coerce.number().nullable(),
  abySystem_Effect_Type_0: z.coerce.number().nullable(),
  aSystem_Effect_Value_0: z.coerce.number().nullable(),
  aSystem_Effect_1: z.coerce.number().nullable(),
  abySystem_Effect_Type_1: z.coerce.number().nullable(),
  aSystem_Effect_Value_1: z.coerce.number().nullable(),
  aSystem_Effect_2: z.coerce.number().nullable(),
  abySystem_Effect_Type_2: z.coerce.number().nullable(),
  aSystem_Effect_Value_2: z.coerce.number().nullable(),
  aSystem_Effect_3: z.coerce.number().nullable(),
  abySystem_Effect_Type_3: z.coerce.number().nullable(),
  aSystem_Effect_Value_3: z.coerce.number().nullable(),
  aSystem_Effect_4: z.coerce.number().nullable(),
  abySystem_Effect_Type_4: z.coerce.number().nullable(),
  aSystem_Effect_Value_4: z.coerce.number().nullable(),
  aSystem_Effect_5: z.coerce.number().nullable(),
  abySystem_Effect_Type_5: z.coerce.number().nullable(),
  aSystem_Effect_Value_5: z.coerce.number().nullable(),
  aSystem_Effect_6: z.coerce.number().nullable(),
  abySystem_Effect_Type_6: z.coerce.number().nullable(),
  aSystem_Effect_Value_6: z.coerce.number().nullable(),
  aSystem_Effect_7: z.coerce.number().nullable(),
  abySystem_Effect_Type_7: z.coerce.number().nullable(),
  aSystem_Effect_Value_7: z.coerce.number().nullable(),
  aSystem_Effect_8: z.coerce.number().nullable(),
  abySystem_Effect_Type_8: z.coerce.number().nullable(),
  aSystem_Effect_Value_8: z.coerce.number().nullable(),
  aSystem_Effect_9: z.coerce.number().nullable(),
  abySystem_Effect_Type_9: z.coerce.number().nullable(),
  aSystem_Effect_Value_9: z.coerce.number().nullable(),
});

export type UseItemFormData = z.infer<typeof useItemSchema>;

export const columns = [
  { key: 'tblidx', label: 'ID', type: 'number' as const, validation: useItemSchema.shape.tblidx },
  { key: 'byUse_Item_Active_Type', label: 'Active Type', type: 'number' as const, validation: useItemSchema.shape.byUse_Item_Active_Type },
  { key: 'byBuff_Group', label: 'Buff Group', type: 'number' as const, validation: useItemSchema.shape.byBuff_Group },
  { key: 'byBuffKeepType', label: 'Buff Keep Type', type: 'number' as const, validation: useItemSchema.shape.byBuffKeepType },
  { key: 'Use_Info_Text', label: 'Info Text', type: 'number' as const, validation: useItemSchema.shape.Use_Info_Text },
  { key: 'dwCool_Time_Bit_Flag', label: 'Cool Time Bit Flag', type: 'number' as const, validation: useItemSchema.shape.dwCool_Time_Bit_Flag },
  { key: 'wFunction_Bit_Flag', label: 'Function Bit Flag', type: 'number' as const, validation: useItemSchema.shape.wFunction_Bit_Flag },
  { key: 'dwUse_Restriction_Rule_Bit_Flag', label: 'Use Restriction Rule', type: 'number' as const, validation: useItemSchema.shape.dwUse_Restriction_Rule_Bit_Flag },
  { key: 'dwUse_Allow_Rule_Bit_Flag', label: 'Use Allow Rule', type: 'number' as const, validation: useItemSchema.shape.dwUse_Allow_Rule_Bit_Flag },
  { key: 'wNeed_State_Bit_Flag', label: 'Need State Flag', type: 'number' as const, validation: useItemSchema.shape.wNeed_State_Bit_Flag },
  { key: 'byAppoint_Target', label: 'Appoint Target', type: 'number' as const, validation: useItemSchema.shape.byAppoint_Target },
  { key: 'byApply_Target', label: 'Apply Target', type: 'number' as const, validation: useItemSchema.shape.byApply_Target },
  { key: 'dwApply_Target_Index', label: 'Apply Target Index', type: 'number' as const, validation: useItemSchema.shape.dwApply_Target_Index },
  { key: 'byApply_Target_Max', label: 'Apply Target Max', type: 'number' as const, validation: useItemSchema.shape.byApply_Target_Max },
  { key: 'byApply_Range', label: 'Apply Range', type: 'number' as const, validation: useItemSchema.shape.byApply_Range },
  { key: 'byApply_Area_Size_1', label: 'Area Size 1', type: 'number' as const, validation: useItemSchema.shape.byApply_Area_Size_1 },
  { key: 'byApply_Area_Size_2', label: 'Area Size 2', type: 'number' as const, validation: useItemSchema.shape.byApply_Area_Size_2 },
  { key: 'dwRequire_LP', label: 'Required LP', type: 'number' as const, validation: useItemSchema.shape.dwRequire_LP },
  { key: 'wRequire_EP', label: 'Required EP', type: 'number' as const, validation: useItemSchema.shape.wRequire_EP },
  { key: 'byRequire_RP_Ball', label: 'Required RP Ball', type: 'number' as const, validation: useItemSchema.shape.byRequire_RP_Ball },
  { key: 'RequiredQuestID', label: 'Required Quest ID', type: 'number' as const, validation: useItemSchema.shape.RequiredQuestID },
  { key: 'fCasting_Time', label: 'Casting Time', type: 'number' as const, validation: useItemSchema.shape.fCasting_Time },
  { key: 'dwCastingTimeInMilliSecs', label: 'Casting Time (ms)', type: 'number' as const, validation: useItemSchema.shape.dwCastingTimeInMilliSecs },
  { key: 'dwCool_Time', label: 'Cool Time', type: 'number' as const, validation: useItemSchema.shape.dwCool_Time },
  { key: 'dwCoolTimeInMilliSecs', label: 'Cool Time (ms)', type: 'number' as const, validation: useItemSchema.shape.dwCoolTimeInMilliSecs },
  { key: 'dwKeep_Time', label: 'Keep Time', type: 'number' as const, validation: useItemSchema.shape.dwKeep_Time },
  { key: 'dwKeepTimeInMilliSecs', label: 'Keep Time (ms)', type: 'number' as const, validation: useItemSchema.shape.dwKeepTimeInMilliSecs },
  { key: 'bKeep_Effect', label: 'Keep Effect', type: 'boolean' as const, validation: useItemSchema.shape.bKeep_Effect },
  { key: 'byUse_Range_Min', label: 'Use Range Min', type: 'number' as const, validation: useItemSchema.shape.byUse_Range_Min },
  { key: 'fUse_Range_Min', label: 'Use Range Min (Float)', type: 'number' as const, validation: useItemSchema.shape.fUse_Range_Min },
  { key: 'byUse_Range_Max', label: 'Use Range Max', type: 'number' as const, validation: useItemSchema.shape.byUse_Range_Max },
  { key: 'fUse_Range_Max', label: 'Use Range Max (Float)', type: 'number' as const, validation: useItemSchema.shape.fUse_Range_Max },
  { key: 'szCasting_Effect', label: 'Casting Effect', type: 'text' as const, validation: useItemSchema.shape.szCasting_Effect },
  { key: 'szAction_Effect', label: 'Action Effect', type: 'text' as const, validation: useItemSchema.shape.szAction_Effect },
  { key: 'wCasting_Animation_Start', label: 'Casting Animation Start', type: 'number' as const, validation: useItemSchema.shape.wCasting_Animation_Start },
  { key: 'wCasting_Animation_Loop', label: 'Casting Animation Loop', type: 'number' as const, validation: useItemSchema.shape.wCasting_Animation_Loop },
  { key: 'wAction_Animation_Index', label: 'Action Animation Index', type: 'number' as const, validation: useItemSchema.shape.wAction_Animation_Index },
  { key: 'wAction_Loop_Animation_Index', label: 'Action Loop Animation', type: 'number' as const, validation: useItemSchema.shape.wAction_Loop_Animation_Index },
  { key: 'wAction_End_Animation_Index', label: 'Action End Animation', type: 'number' as const, validation: useItemSchema.shape.wAction_End_Animation_Index },
  { key: 'byCastingEffectPosition', label: 'Casting Effect Position', type: 'number' as const, validation: useItemSchema.shape.byCastingEffectPosition },
  { key: 'byActionEffectPosition', label: 'Action Effect Position', type: 'number' as const, validation: useItemSchema.shape.byActionEffectPosition },
  { key: 'useWorldTblidx', label: 'Use World ID', type: 'number' as const, validation: useItemSchema.shape.useWorldTblidx },
  { key: 'fUseLoc_X', label: 'Use Location X', type: 'number' as const, validation: useItemSchema.shape.fUseLoc_X },
  { key: 'fUseLoc_Z', label: 'Use Location Z', type: 'number' as const, validation: useItemSchema.shape.fUseLoc_Z },
  { key: 'fUseLoc_Radius', label: 'Use Location Radius', type: 'number' as const, validation: useItemSchema.shape.fUseLoc_Radius },
  ...Array.from({ length: 10 }, (_, i) => [
    { key: `aSystem_Effect_${i}`, label: `System Effect ${i}`, type: 'number' as const, validation: useItemSchema.shape[`aSystem_Effect_${i}` as keyof typeof useItemSchema.shape] },
    { key: `abySystem_Effect_Type_${i}`, label: `System Effect Type ${i}`, type: 'number' as const, validation: useItemSchema.shape[`abySystem_Effect_Type_${i}` as keyof typeof useItemSchema.shape] },
    { key: `aSystem_Effect_Value_${i}`, label: `System Effect Value ${i}`, type: 'number' as const, validation: useItemSchema.shape[`aSystem_Effect_Value_${i}` as keyof typeof useItemSchema.shape] }
  ]).flat(),
];
