import * as z from "zod";

export const useItemSchema = z.object({
  table_id: z.string().uuid().nullable(),
  tblidx: z.coerce.number().nullable(),
  byuse_item_active_type: z.coerce.number().nullable(),
  bybuff_group: z.coerce.number().nullable(),
  bybuffkeeptype: z.coerce.number().nullable(),
  dwcool_time_bit_flag: z.coerce.number().nullable(),
  wfunction_bit_flag: z.coerce.number().nullable(),
  dwuse_restriction_rule_bit_flag: z.coerce.number().nullable(),
  dwuse_allow_rule_bit_flag: z.coerce.number().nullable(),
  byappoint_target: z.coerce.number().nullable(),
  byapply_target: z.coerce.number().nullable(),
  dwapply_target_index: z.coerce.number().nullable(),
  byapply_target_max: z.coerce.number().nullable(),
  byapply_range: z.coerce.number().nullable(),
  byapply_area_size_1: z.coerce.number().nullable(),
  byapply_area_size_2: z.coerce.number().nullable(),
  wneed_state_bit_flag: z.coerce.number().nullable(),
  dwrequire_lp: z.coerce.number().nullable(),
  wrequire_ep: z.coerce.number().nullable(),
  byrequire_rp_ball: z.coerce.number().nullable(),
  fcasting_time: z.coerce.number().nullable(),
  dwcastingtimeinmillisecs: z.coerce.number().nullable(),
  dwcool_time: z.coerce.number().nullable(),
  dwcooltimeinmillisecs: z.coerce.number().nullable(),
  dwkeep_time: z.coerce.number().nullable(),
  dwkeeptimeinmillisecs: z.coerce.number().nullable(),
  bkeep_effect: z.coerce.number().nullable(),
  byuse_range_min: z.coerce.number().nullable(),
  fuse_range_min: z.coerce.number().nullable(),
  byuse_range_max: z.coerce.number().nullable(),
  fuse_range_max: z.coerce.number().nullable(),
  use_info_text: z.string().nullable(),
  szcasting_effect: z.string().nullable(),
  szaction_effect: z.string().nullable(),
  wcasting_animation_start: z.coerce.number().nullable(),
  wcasting_animation_loop: z.coerce.number().nullable(),
  waction_animation_index: z.coerce.number().nullable(),
  waction_loop_animation_index: z.coerce.number().nullable(),
  waction_end_animation_index: z.coerce.number().nullable(),
  bycastingeffectposition: z.coerce.number().nullable(),
  byactioneffectposition: z.coerce.number().nullable(),
  useworldtblidx: z.coerce.number().nullable(),
  fuseloc_x: z.coerce.number().nullable(),
  fuseloc_z: z.coerce.number().nullable(),
  fuseloc_radius: z.coerce.number().nullable(),
  requiredquestid: z.coerce.number().nullable(),
  asystem_effect_0: z.coerce.number().nullable(),
  abysystem_effect_type_0: z.coerce.number().nullable(),
  asystem_effect_value_0: z.coerce.number().nullable(),
  asystem_effect_1: z.coerce.number().nullable(),
  abysystem_effect_type_1: z.coerce.number().nullable(),
  asystem_effect_value_1: z.coerce.number().nullable(),
});

export type UseItemFormData = z.infer<typeof useItemSchema>;

export const columns = [
  { key: 'tblidx', label: 'ID', type: 'number' as const, validation: useItemSchema.shape.tblidx },
  { key: 'byuse_item_active_type', label: 'Active Type', type: 'number' as const, validation: useItemSchema.shape.byuse_item_active_type },
  { key: 'bybuff_group', label: 'Buff Group', type: 'number' as const, validation: useItemSchema.shape.bybuff_group },
  { key: 'bybuffkeeptype', label: 'Buff Keep Type', type: 'number' as const, validation: useItemSchema.shape.bybuffkeeptype },
  { key: 'use_info_text', label: 'Info Text', type: 'text' as const, validation: useItemSchema.shape.use_info_text },
  { key: 'dwcool_time_bit_flag', label: 'Cool Time Bit Flag', type: 'number' as const, validation: useItemSchema.shape.dwcool_time_bit_flag },
  { key: 'wfunction_bit_flag', label: 'Function Bit Flag', type: 'number' as const, validation: useItemSchema.shape.wfunction_bit_flag },
  { key: 'dwuse_restriction_rule_bit_flag', label: 'Use Restriction Rule', type: 'number' as const, validation: useItemSchema.shape.dwuse_restriction_rule_bit_flag },
  { key: 'dwuse_allow_rule_bit_flag', label: 'Use Allow Rule', type: 'number' as const, validation: useItemSchema.shape.dwuse_allow_rule_bit_flag },
  { key: 'wneed_state_bit_flag', label: 'Need State Flag', type: 'number' as const, validation: useItemSchema.shape.wneed_state_bit_flag },
  { key: 'byappoint_target', label: 'Appoint Target', type: 'number' as const, validation: useItemSchema.shape.byappoint_target },
  { key: 'byapply_target', label: 'Apply Target', type: 'number' as const, validation: useItemSchema.shape.byapply_target },
  { key: 'dwapply_target_index', label: 'Apply Target Index', type: 'number' as const, validation: useItemSchema.shape.dwapply_target_index },
  { key: 'byapply_target_max', label: 'Apply Target Max', type: 'number' as const, validation: useItemSchema.shape.byapply_target_max },
  { key: 'byapply_range', label: 'Apply Range', type: 'number' as const, validation: useItemSchema.shape.byapply_range },
  { key: 'byapply_area_size_1', label: 'Area Size 1', type: 'number' as const, validation: useItemSchema.shape.byapply_area_size_1 },
  { key: 'byapply_area_size_2', label: 'Area Size 2', type: 'number' as const, validation: useItemSchema.shape.byapply_area_size_2 },
  { key: 'dwrequire_lp', label: 'Required LP', type: 'number' as const, validation: useItemSchema.shape.dwrequire_lp },
  { key: 'wrequire_ep', label: 'Required EP', type: 'number' as const, validation: useItemSchema.shape.wrequire_ep },
  { key: 'byrequire_rp_ball', label: 'Required RP Ball', type: 'number' as const, validation: useItemSchema.shape.byrequire_rp_ball },
  { key: 'requiredquestid', label: 'Required Quest ID', type: 'number' as const, validation: useItemSchema.shape.requiredquestid },
  { key: 'fcasting_time', label: 'Casting Time', type: 'number' as const, validation: useItemSchema.shape.fcasting_time },
  { key: 'dwcastingtimeinmillisecs', label: 'Casting Time (ms)', type: 'number' as const, validation: useItemSchema.shape.dwcastingtimeinmillisecs },
  { key: 'dwcool_time', label: 'Cool Time', type: 'number' as const, validation: useItemSchema.shape.dwcool_time },
  { key: 'dwcooltimeinmillisecs', label: 'Cool Time (ms)', type: 'number' as const, validation: useItemSchema.shape.dwcooltimeinmillisecs },
  { key: 'dwkeep_time', label: 'Keep Time', type: 'number' as const, validation: useItemSchema.shape.dwkeep_time },
  { key: 'dwkeeptimeinmillisecs', label: 'Keep Time (ms)', type: 'number' as const, validation: useItemSchema.shape.dwkeeptimeinmillisecs },
  { key: 'bkeep_effect', label: 'Keep Effect', type: 'number' as const, validation: useItemSchema.shape.bkeep_effect },
  { key: 'byuse_range_min', label: 'Use Range Min', type: 'number' as const, validation: useItemSchema.shape.byuse_range_min },
  { key: 'fuse_range_min', label: 'Use Range Min (Float)', type: 'number' as const, validation: useItemSchema.shape.fuse_range_min },
  { key: 'byuse_range_max', label: 'Use Range Max', type: 'number' as const, validation: useItemSchema.shape.byuse_range_max },
  { key: 'fuse_range_max', label: 'Use Range Max (Float)', type: 'number' as const, validation: useItemSchema.shape.fuse_range_max },
  { key: 'szcasting_effect', label: 'Casting Effect', type: 'text' as const, validation: useItemSchema.shape.szcasting_effect },
  { key: 'szaction_effect', label: 'Action Effect', type: 'text' as const, validation: useItemSchema.shape.szaction_effect },
  { key: 'wcasting_animation_start', label: 'Casting Animation Start', type: 'number' as const, validation: useItemSchema.shape.wcasting_animation_start },
  { key: 'wcasting_animation_loop', label: 'Casting Animation Loop', type: 'number' as const, validation: useItemSchema.shape.wcasting_animation_loop },
  { key: 'waction_animation_index', label: 'Action Animation Index', type: 'number' as const, validation: useItemSchema.shape.waction_animation_index },
  { key: 'waction_loop_animation_index', label: 'Action Loop Animation', type: 'number' as const, validation: useItemSchema.shape.waction_loop_animation_index },
  { key: 'waction_end_animation_index', label: 'Action End Animation', type: 'number' as const, validation: useItemSchema.shape.waction_end_animation_index },
  { key: 'bycastingeffectposition', label: 'Casting Effect Position', type: 'number' as const, validation: useItemSchema.shape.bycastingeffectposition },
  { key: 'byactioneffectposition', label: 'Action Effect Position', type: 'number' as const, validation: useItemSchema.shape.byactioneffectposition },
  { key: 'useworldtblidx', label: 'Use World ID', type: 'number' as const, validation: useItemSchema.shape.useworldtblidx },
  { key: 'fuseloc_x', label: 'Use Location X', type: 'number' as const, validation: useItemSchema.shape.fuseloc_x },
  { key: 'fuseloc_z', label: 'Use Location Z', type: 'number' as const, validation: useItemSchema.shape.fuseloc_z },
  { key: 'fuseloc_radius', label: 'Use Location Radius', type: 'number' as const, validation: useItemSchema.shape.fuseloc_radius },
  ...Array.from({ length: 2 }, (_, i) => [
    { key: `asystem_effect_${i}`, label: `System Effect ${i}`, type: 'number' as const, validation: useItemSchema.shape[`asystem_effect_${i}` as keyof typeof useItemSchema.shape] },
    { key: `abysystem_effect_type_${i}`, label: `System Effect Type ${i}`, type: 'number' as const, validation: useItemSchema.shape[`abysystem_effect_type_${i}` as keyof typeof useItemSchema.shape] },
    { key: `asystem_effect_value_${i}`, label: `System Effect Value ${i}`, type: 'number' as const, validation: useItemSchema.shape[`asystem_effect_value_${i}` as keyof typeof useItemSchema.shape] }
  ]).flat(),
]; 