import { z } from "zod";

// Define the schema for the skill table
export const skillSchema = z.object({
  id: z.string().uuid().optional(),
  table_id: z.string().uuid().optional(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
  tblidx: z.number().optional(),
  Skill_Name: z.number().nullable().optional(),
  wszNameText: z.string().nullable().transform(e => e === null ? "" : e).optional(),
  bValidity_Able: z.coerce.boolean().nullable().transform(val => val ? 1 : 0).optional(),
  dwPC_Class_Bit_Flag: z.number().nullable().optional(),
  byClass_Type: z.number().nullable().optional(),
  bySkill_Class: z.number().nullable().optional(),
  bySkill_Type: z.number().nullable().optional(),
  bySkill_Active_Type: z.number().nullable().optional(),
  byBuff_Group: z.number().nullable().optional(),
  bySlot_Index: z.number().nullable().optional(),
  bySkill_Grade: z.number().nullable().optional(),
  dwFunction_Bit_Flag: z.number().nullable().optional(),
  byAppoint_Target: z.number().nullable().optional(),
  byApply_Target: z.number().nullable().optional(),
  byApply_Target_Max: z.number().nullable().optional(),
  byApply_Range: z.number().nullable().optional(),
  byApply_Area_Size_1: z.number().nullable().optional(),
  byApply_Area_Size_2: z.number().nullable().optional(),
  dwAdditional_Aggro_Point: z.number().nullable().optional(),
  byRequire_Train_Level: z.number().nullable().optional(),
  dwRequire_Zenny: z.number().nullable().optional(),
  wNext_Skill_Train_Exp: z.number().nullable().optional(),
  Root_Skill: z.number().nullable().optional(),
  byRequire_Epuip_Slot_Type: z.number().nullable().optional(),
  byRequire_Item_Type: z.number().nullable().optional(),
  szIcon_Name: z.string().nullable().transform(e => e === null ? "" : e).optional(),
  dwRequire_LP: z.number().nullable().optional(),
  wRequire_EP: z.number().nullable().optional(),
  byRequire_RP_Ball: z.number().nullable().optional(),
  fCasting_Time: z.number().nullable().optional(),
  dwCastingTimeInMilliSecs: z.number().nullable().optional(),
  wCool_Time: z.number().nullable().optional(),
  dwCoolTimeInMilliSecs: z.number().nullable().optional(),
  wKeep_Time: z.number().nullable().optional(),
  dwKeepTimeInMilliSecs: z.number().nullable().optional(),
  bKeep_Effect: z.coerce.boolean().nullable().transform(val => val ? 1 : 0).optional(),
  byUse_Range_Min: z.number().nullable().optional(),
  fUse_Range_Min: z.number().nullable().optional(),
  byUse_Range_Max: z.number().nullable().optional(),
  fUse_Range_Max: z.number().nullable().optional(),
  Note: z.number().nullable().optional(),
  dwNextSkillTblidx: z.number().nullable().optional(),
  bDefaultDisplayOff: z.coerce.boolean().nullable().transform(val => val ? 1 : 0).optional(),
  dwAnimation_Time: z.number().nullable().optional(),
  wCasting_Animation_Start: z.number().nullable().optional(),
  wCasting_Animation_Loop: z.number().nullable().optional(),
  wAction_Animation_Index: z.number().nullable().optional(),
  wAction_Loop_Animation_Index: z.number().nullable().optional(),
  wAction_End_Animation_Index: z.number().nullable().optional(),
  bDash_Able: z.coerce.boolean().nullable().transform(val => val ? 1 : 0).optional(),
  dwTransform_Use_Info_Bit_Flag: z.number().nullable().optional(),
  fSuccess_Rate: z.number().nullable().optional(),
  byPC_Class_Change: z.number().nullable().optional(),
  byUse_Type: z.number().nullable().optional(),
  bySkill_Group: z.number().nullable().optional(),
  dwRequire_VP: z.number().nullable().optional(),
  dwUse_Restriction_Rule_Bit_Flag: z.number().nullable().optional(),
  skill_Effect_0: z.number().nullable().optional(),
  bySkill_Effect_Type_0: z.number().nullable().optional(),
  aSkill_Effect_Value_0: z.number().nullable().optional(),
  skill_Effect_1: z.number().nullable().optional(),
  bySkill_Effect_Type_1: z.number().nullable().optional(),
  aSkill_Effect_Value_1: z.number().nullable().optional(),
  skill_Effect_2: z.number().nullable().optional(),
  bySkill_Effect_Type_2: z.number().nullable().optional(),
  aSkill_Effect_Value_2: z.number().nullable().optional(),
  skill_Effect_3: z.number().nullable().optional(),
  bySkill_Effect_Type_3: z.number().nullable().optional(),
  aSkill_Effect_Value_3: z.number().nullable().optional(),
  skill_Effect_4: z.number().nullable().optional(),
  bySkill_Effect_Type_4: z.number().nullable().optional(),
  aSkill_Effect_Value_4: z.number().nullable().optional(),
  skill_Effect_5: z.number().nullable().optional(),
  bySkill_Effect_Type_5: z.number().nullable().optional(),
  aSkill_Effect_Value_5: z.number().nullable().optional(),
  skill_Effect_6: z.number().nullable().optional(),
  bySkill_Effect_Type_6: z.number().nullable().optional(),
  aSkill_Effect_Value_6: z.number().nullable().optional(),
  skill_Effect_7: z.number().nullable().optional(),
  bySkill_Effect_Type_7: z.number().nullable().optional(),
  aSkill_Effect_Value_7: z.number().nullable().optional(),
  skill_Effect_8: z.number().nullable().optional(),
  bySkill_Effect_Type_8: z.number().nullable().optional(),
  aSkill_Effect_Value_8: z.number().nullable().optional(),
  skill_Effect_9: z.number().nullable().optional(),
  bySkill_Effect_Type_9: z.number().nullable().optional(),
  aSkill_Effect_Value_9: z.number().nullable().optional(),
  abyRpEffect_0: z.number().nullable().optional(),
  afRpEffectValue_0: z.number().nullable().optional(),
  abyRpEffect_1: z.number().nullable().optional(),
  afRpEffectValue_1: z.number().nullable().optional(),
  abyRpEffect_2: z.number().nullable().optional(),
  afRpEffectValue_2: z.number().nullable().optional(),
  abyRpEffect_3: z.number().nullable().optional(),
  afRpEffectValue_3: z.number().nullable().optional(),
  abyRpEffect_4: z.number().nullable().optional(),
  afRpEffectValue_4: z.number().nullable().optional(),
});

export type SkillFormData = z.infer<typeof skillSchema>;

export const columns = [
  { key: 'tblidx', label: 'ID', type: 'number' as const, validation: skillSchema.shape.tblidx },
  { key: 'Skill_Name', label: 'Skill Name', type: 'number' as const, validation: skillSchema.shape.Skill_Name },
  { key: 'wszNameText', label: 'Display Name', type: 'text' as const, validation: skillSchema.shape.wszNameText },
  { key: 'szIcon_Name', label: 'Icon Name', type: 'text' as const, validation: skillSchema.shape.szIcon_Name },
  { key: 'Note', label: 'Note', type: 'number' as const, validation: skillSchema.shape.Note },
  { key: 'byClass_Type', label: 'Class Type', type: 'number' as const, validation: skillSchema.shape.byClass_Type },
  { key: 'bySkill_Class', label: 'Skill Class', type: 'number' as const, validation: skillSchema.shape.bySkill_Class },
  { key: 'bySkill_Type', label: 'Skill Type', type: 'number' as const, validation: skillSchema.shape.bySkill_Type },
  { key: 'bySkill_Active_Type', label: 'Active Type', type: 'number' as const, validation: skillSchema.shape.bySkill_Active_Type },
  { key: 'bySkill_Grade', label: 'Skill Grade', type: 'number' as const, validation: skillSchema.shape.bySkill_Grade },
  { key: 'bySkill_Group', label: 'Skill Group', type: 'number' as const, validation: skillSchema.shape.bySkill_Group },
  { key: 'byRequire_Train_Level', label: 'Required Level', type: 'number' as const, validation: skillSchema.shape.byRequire_Train_Level },
  { key: 'dwRequire_Zenny', label: 'Required Zenny', type: 'number' as const, validation: skillSchema.shape.dwRequire_Zenny },
  { key: 'dwRequire_LP', label: 'Required LP', type: 'number' as const, validation: skillSchema.shape.dwRequire_LP },
  { key: 'wRequire_EP', label: 'Required EP', type: 'number' as const, validation: skillSchema.shape.wRequire_EP },
  { key: 'dwRequire_VP', label: 'Required VP', type: 'number' as const, validation: skillSchema.shape.dwRequire_VP },
  { key: 'byRequire_RP_Ball', label: 'Required RP Ball', type: 'number' as const, validation: skillSchema.shape.byRequire_RP_Ball },
  { key: 'fCasting_Time', label: 'Cast Time', type: 'number' as const, validation: skillSchema.shape.fCasting_Time },
  { key: 'dwCastingTimeInMilliSecs', label: 'Cast Time (ms)', type: 'number' as const, validation: skillSchema.shape.dwCastingTimeInMilliSecs },
  { key: 'wCool_Time', label: 'Cooldown', type: 'number' as const, validation: skillSchema.shape.wCool_Time },
  { key: 'dwCoolTimeInMilliSecs', label: 'Cooldown (ms)', type: 'number' as const, validation: skillSchema.shape.dwCoolTimeInMilliSecs },
  { key: 'wKeep_Time', label: 'Duration', type: 'number' as const, validation: skillSchema.shape.wKeep_Time },
  { key: 'dwKeepTimeInMilliSecs', label: 'Duration (ms)', type: 'number' as const, validation: skillSchema.shape.dwKeepTimeInMilliSecs },
  { key: 'byAppoint_Target', label: 'Appoint Target', type: 'number' as const, validation: skillSchema.shape.byAppoint_Target },
  { key: 'byApply_Target', label: 'Apply Target', type: 'number' as const, validation: skillSchema.shape.byApply_Target },
  { key: 'byApply_Target_Max', label: 'Max Targets', type: 'number' as const, validation: skillSchema.shape.byApply_Target_Max },
  { key: 'byApply_Range', label: 'Apply Range', type: 'number' as const, validation: skillSchema.shape.byApply_Range },
  { key: 'byUse_Range_Min', label: 'Min Range', type: 'number' as const, validation: skillSchema.shape.byUse_Range_Min },
  { key: 'byUse_Range_Max', label: 'Max Range', type: 'number' as const, validation: skillSchema.shape.byUse_Range_Max },
  ...Array.from({ length: 10 }, (_, i) => [
    { key: `skill_Effect_${i}`, label: `Effect ${i + 1}`, type: 'number' as const, validation: skillSchema.shape[`skill_Effect_${i}` as keyof typeof skillSchema.shape] },
    { key: `bySkill_Effect_Type_${i}`, label: `Effect ${i + 1} Type`, type: 'number' as const, validation: skillSchema.shape[`bySkill_Effect_Type_${i}` as keyof typeof skillSchema.shape] },
    { key: `aSkill_Effect_Value_${i}`, label: `Effect ${i + 1} Value`, type: 'number' as const, validation: skillSchema.shape[`aSkill_Effect_Value_${i}` as keyof typeof skillSchema.shape] }
  ]).flat(),
  ...Array.from({ length: 5 }, (_, i) => [
    { key: `abyRpEffect_${i}`, label: `RP Effect ${i + 1}`, type: 'number' as const, validation: skillSchema.shape[`abyRpEffect_${i}` as keyof typeof skillSchema.shape] },
    { key: `afRpEffectValue_${i}`, label: `RP Effect ${i + 1} Value`, type: 'number' as const, validation: skillSchema.shape[`afRpEffectValue_${i}` as keyof typeof skillSchema.shape] }
  ]).flat(),
];
