import { z } from "zod";

// Define the schema for the skill table
export const skillSchema = z.object({
  id: z.string().uuid().optional(),
  table_id: z.string().uuid().optional(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
  tblidx: z.number().optional(),
  skill_name: z.string().optional(),
  wsznametext: z.string().optional(),
  bvalidity_able: z.number().optional(),
  dwpc_class_bit_flag: z.number().optional(),
  byclass_type: z.number().optional(),
  byskill_class: z.number().optional(),
  byskill_type: z.number().optional(),
  byskill_active_type: z.number().optional(),
  bybuff_group: z.number().optional(),
  byslot_index: z.number().optional(),
  byskill_grade: z.number().optional(),
  dwfunction_bit_flag: z.number().optional(),
  byappoint_target: z.number().optional(),
  byapply_target: z.number().optional(),
  byapply_target_max: z.number().optional(),
  byapply_range: z.number().optional(),
  byapply_area_size_1: z.number().optional(),
  byapply_area_size_2: z.number().optional(),
  dwadditional_aggro_point: z.number().optional(),
  byrequire_train_level: z.number().optional(),
  dwrequire_zenny: z.number().optional(),
  wnext_skill_train_exp: z.number().optional(),
  wrequiresp: z.number().optional(),
  bselftrain: z.number().optional(),
  uirequire_skill_tblidx_min_1: z.number().optional(),
  uirequire_skill_tblidx_max_1: z.number().optional(),
  uirequire_skill_tblidx_min_2: z.number().optional(),
  uirequire_skill_tblidx_max_2: z.number().optional(),
  root_skill: z.number().optional(),
  byrequire_epuip_slot_type: z.number().optional(),
  byrequire_item_type: z.number().optional(),
  szicon_name: z.string().optional(),
  dwrequire_lp: z.number().optional(),
  wrequire_ep: z.number().optional(),
  byrequire_rp_ball: z.number().optional(),
  fcasting_time: z.number().optional(),
  dwcastingtimeinmillisecs: z.number().optional(),
  wcool_time: z.number().optional(),
  dwcooltimeinmillisecs: z.number().optional(),
  wkeep_time: z.number().optional(),
  dwkeeptimeinmillisecs: z.number().optional(),
  bkeep_effect: z.number().optional(),
  byuse_range_min: z.number().optional(),
  fuse_range_min: z.number().optional(),
  byuse_range_max: z.number().optional(),
  fuse_range_max: z.number().optional(),
  note: z.string().optional(),
  dwnextskilltblidx: z.number().optional(),
  bdefaultdisplayoff: z.number().optional(),
  dwanimation_time: z.number().optional(),
  wcasting_animation_start: z.number().optional(),
  wcasting_animation_loop: z.number().optional(),
  waction_animation_index: z.number().optional(),
  waction_loop_animation_index: z.number().optional(),
  waction_end_animation_index: z.number().optional(),
  bdash_able: z.number().optional(),
  dwtransform_use_info_bit_flag: z.number().optional(),
  fsuccess_rate: z.number().optional(),
  bypc_class_change: z.number().optional(),
  byuse_type: z.number().optional(),
  byskill_group: z.number().optional(),
  dwrequire_vp: z.number().optional(),
  dwuse_restriction_rule_bit_flag: z.number().optional(),
  skill_effect_0: z.number().optional(),
  byskill_effect_type_0: z.number().optional(),
  askill_effect_value_0: z.number().optional(),
  skill_effect_1: z.number().optional(),
  byskill_effect_type_1: z.number().optional(),
  askill_effect_value_1: z.number().optional(),
  abyrpeffect_0: z.number().optional(),
  afrpeffectvalue_0: z.number().optional(),
  abyrpeffect_1: z.number().optional(),
  afrpeffectvalue_1: z.number().optional(),
  abyrpeffect_2: z.number().optional(),
  afrpeffectvalue_2: z.number().optional(),
  abyrpeffect_3: z.number().optional(),
  afrpeffectvalue_3: z.number().optional(),
  abyrpeffect_4: z.number().optional(),
  afrpeffectvalue_4: z.number().optional(),
  abyrpeffect_5: z.number().optional(),
  afrpeffectvalue_5: z.number().optional(),
});

export type SkillFormData = z.infer<typeof skillSchema>;

export const columns = [
  { key: 'tblidx', label: 'ID', type: 'number' as const, validation: skillSchema.shape.tblidx },
  { key: 'skill_name', label: 'Skill Name', type: 'text' as const, validation: skillSchema.shape.skill_name },
  { key: 'wsznametext', label: 'Display Name', type: 'text' as const, validation: skillSchema.shape.wsznametext },
  { key: 'szicon_name', label: 'Icon Name', type: 'text' as const, validation: skillSchema.shape.szicon_name },
  { key: 'note', label: 'Note', type: 'text' as const, validation: skillSchema.shape.note },
  { key: 'byclass_type', label: 'Class Type', type: 'number' as const, validation: skillSchema.shape.byclass_type },
  { key: 'byskill_class', label: 'Skill Class', type: 'number' as const, validation: skillSchema.shape.byskill_class },
  { key: 'byskill_type', label: 'Skill Type', type: 'number' as const, validation: skillSchema.shape.byskill_type },
  { key: 'byskill_active_type', label: 'Active Type', type: 'number' as const, validation: skillSchema.shape.byskill_active_type },
  { key: 'byskill_grade', label: 'Skill Grade', type: 'number' as const, validation: skillSchema.shape.byskill_grade },
  { key: 'byskill_group', label: 'Skill Group', type: 'number' as const, validation: skillSchema.shape.byskill_group },
  { key: 'byrequire_train_level', label: 'Required Level', type: 'number' as const, validation: skillSchema.shape.byrequire_train_level },
  { key: 'dwrequire_zenny', label: 'Required Zenny', type: 'number' as const, validation: skillSchema.shape.dwrequire_zenny },
  { key: 'wrequiresp', label: 'Required SP', type: 'number' as const, validation: skillSchema.shape.wrequiresp },
  { key: 'dwrequire_lp', label: 'Required LP', type: 'number' as const, validation: skillSchema.shape.dwrequire_lp },
  { key: 'wrequire_ep', label: 'Required EP', type: 'number' as const, validation: skillSchema.shape.wrequire_ep },
  { key: 'dwrequire_vp', label: 'Required VP', type: 'number' as const, validation: skillSchema.shape.dwrequire_vp },
  { key: 'byrequire_rp_ball', label: 'Required RP Ball', type: 'number' as const, validation: skillSchema.shape.byrequire_rp_ball },
  { key: 'fcasting_time', label: 'Cast Time', type: 'number' as const, validation: skillSchema.shape.fcasting_time },
  { key: 'dwcastingtimeinmillisecs', label: 'Cast Time (ms)', type: 'number' as const, validation: skillSchema.shape.dwcastingtimeinmillisecs },
  { key: 'wcool_time', label: 'Cooldown', type: 'number' as const, validation: skillSchema.shape.wcool_time },
  { key: 'dwcooltimeinmillisecs', label: 'Cooldown (ms)', type: 'number' as const, validation: skillSchema.shape.dwcooltimeinmillisecs },
  { key: 'wkeep_time', label: 'Duration', type: 'number' as const, validation: skillSchema.shape.wkeep_time },
  { key: 'dwkeeptimeinmillisecs', label: 'Duration (ms)', type: 'number' as const, validation: skillSchema.shape.dwkeeptimeinmillisecs },
  { key: 'byappoint_target', label: 'Appoint Target', type: 'number' as const, validation: skillSchema.shape.byappoint_target },
  { key: 'byapply_target', label: 'Apply Target', type: 'number' as const, validation: skillSchema.shape.byapply_target },
  { key: 'byapply_target_max', label: 'Max Targets', type: 'number' as const, validation: skillSchema.shape.byapply_target_max },
  { key: 'byapply_range', label: 'Apply Range', type: 'number' as const, validation: skillSchema.shape.byapply_range },
  { key: 'byuse_range_min', label: 'Min Range', type: 'number' as const, validation: skillSchema.shape.byuse_range_min },
  { key: 'byuse_range_max', label: 'Max Range', type: 'number' as const, validation: skillSchema.shape.byuse_range_max },
  { key: 'skill_effect_0', label: 'Effect 1', type: 'number' as const, validation: skillSchema.shape.skill_effect_0 },
  { key: 'byskill_effect_type_0', label: 'Effect 1 Type', type: 'number' as const, validation: skillSchema.shape.byskill_effect_type_0 },
  { key: 'askill_effect_value_0', label: 'Effect 1 Value', type: 'number' as const, validation: skillSchema.shape.askill_effect_value_0 },
  { key: 'skill_effect_1', label: 'Effect 2', type: 'number' as const, validation: skillSchema.shape.skill_effect_1 },
  { key: 'byskill_effect_type_1', label: 'Effect 2 Type', type: 'number' as const, validation: skillSchema.shape.byskill_effect_type_1 },
  { key: 'askill_effect_value_1', label: 'Effect 2 Value', type: 'number' as const, validation: skillSchema.shape.askill_effect_value_1 },
  { key: 'abyrpeffect_0', label: 'RP Effect 1', type: 'number' as const, validation: skillSchema.shape.abyrpeffect_0 },
  { key: 'afrpeffectvalue_0', label: 'RP Effect 1 Value', type: 'number' as const, validation: skillSchema.shape.afrpeffectvalue_0 },
  { key: 'abyrpeffect_1', label: 'RP Effect 2', type: 'number' as const, validation: skillSchema.shape.abyrpeffect_1 },
  { key: 'afrpeffectvalue_1', label: 'RP Effect 2 Value', type: 'number' as const, validation: skillSchema.shape.afrpeffectvalue_1 },
  { key: 'abyrpeffect_2', label: 'RP Effect 3', type: 'number' as const, validation: skillSchema.shape.abyrpeffect_2 },
  { key: 'afrpeffectvalue_2', label: 'RP Effect 3 Value', type: 'number' as const, validation: skillSchema.shape.afrpeffectvalue_2 },
  { key: 'abyrpeffect_3', label: 'RP Effect 4', type: 'number' as const, validation: skillSchema.shape.abyrpeffect_3 },
  { key: 'afrpeffectvalue_3', label: 'RP Effect 4 Value', type: 'number' as const, validation: skillSchema.shape.afrpeffectvalue_3 },
  { key: 'abyrpeffect_4', label: 'RP Effect 5', type: 'number' as const, validation: skillSchema.shape.abyrpeffect_4 },
  { key: 'afrpeffectvalue_4', label: 'RP Effect 5 Value', type: 'number' as const, validation: skillSchema.shape.afrpeffectvalue_4 },
  { key: 'abyrpeffect_5', label: 'RP Effect 6', type: 'number' as const, validation: skillSchema.shape.abyrpeffect_5 },
  { key: 'afrpeffectvalue_5', label: 'RP Effect 6 Value', type: 'number' as const, validation: skillSchema.shape.afrpeffectvalue_5 },
]; 