import { z } from "zod";

// Define the schema for the item option table
export const itemOptionSchema = z.object({
  table_id: z.string().uuid().optional(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
  tblidx: z.number().optional(),
  wszOption_Name: z.string().nullable().transform(e => e === null ? "" : e).optional(),
  bValidity_Able: z.coerce.boolean().nullable().transform(val => val ? 1 : 0).optional(),
  byOption_Rank: z.coerce.number().nullable().optional(),
  byItem_Group: z.coerce.number().nullable().optional(),
  byMaxQuality: z.coerce.number().nullable().optional(),
  byQuality: z.coerce.number().nullable().optional(),
  byQualityIndex: z.coerce.number().nullable().optional(),
  dwCost: z.coerce.number().nullable().optional(),
  byLevel: z.coerce.number().nullable().optional(),
  activeEffect: z.coerce.number().nullable().optional(),
  fActiveRate: z.coerce.number().nullable().optional(),
  szNote: z.string().nullable().transform(e => e === null ? "" : e).optional(),
  system_Effect_0: z.coerce.number().nullable().optional(),
  bAppliedInPercent_0: z.coerce.boolean().nullable().transform(val => val ? 1 : 0).optional(),
  nValue_0: z.coerce.number().nullable().optional(),
  byScouterInfo_0: z.coerce.number().nullable().optional(),
  system_Effect_1: z.coerce.number().nullable().optional(),
  bAppliedInPercent_1: z.coerce.boolean().nullable().transform(val => val ? 1 : 0).optional(),
  nValue_1: z.coerce.number().nullable().optional(),
  byScouterInfo_1: z.coerce.number().nullable().optional(),
  system_Effect_2: z.coerce.number().nullable().optional(),
  bAppliedInPercent_2: z.coerce.boolean().nullable().transform(val => val ? 1 : 0).optional(),
  nValue_2: z.coerce.number().nullable().optional(),
  byScouterInfo_2: z.coerce.number().nullable().optional(),
  system_Effect_3: z.coerce.number().nullable().optional(),
  bAppliedInPercent_3: z.coerce.boolean().nullable().transform(val => val ? 1 : 0).optional(),
  nValue_3: z.coerce.number().nullable().optional(),
  byScouterInfo_3: z.coerce.number().nullable().optional(),
  system_Effect_4: z.coerce.number().nullable().optional(),
  bAppliedInPercent_4: z.coerce.boolean().nullable().transform(val => val ? 1 : 0).optional(),
  nValue_4: z.coerce.number().nullable().optional(),
  byScouterInfo_4: z.coerce.number().nullable().optional(),
  system_Effect_5: z.coerce.number().nullable().optional(),
  bAppliedInPercent_5: z.coerce.boolean().nullable().transform(val => val ? 1 : 0).optional(),
  nValue_5: z.coerce.number().nullable().optional(),
  byScouterInfo_5: z.coerce.number().nullable().optional(),
  system_Effect_6: z.coerce.number().nullable().optional(),
  bAppliedInPercent_6: z.coerce.boolean().nullable().transform(val => val ? 1 : 0).optional(),
  nValue_6: z.coerce.number().nullable().optional(),
  byScouterInfo_6: z.coerce.number().nullable().optional(),
  system_Effect_7: z.coerce.number().nullable().optional(),
  bAppliedInPercent_7: z.coerce.boolean().nullable().transform(val => val ? 1 : 0).optional(),
  nValue_7: z.coerce.number().nullable().optional(),
  byScouterInfo_7: z.coerce.number().nullable().optional(),
  system_Effect_8: z.coerce.number().nullable().optional(),
  bAppliedInPercent_8: z.coerce.boolean().nullable().transform(val => val ? 1 : 0).optional(),
  nValue_8: z.coerce.number().nullable().optional(),
  byScouterInfo_8: z.coerce.number().nullable().optional(),
  system_Effect_9: z.coerce.number().nullable().optional(),
  bAppliedInPercent_9: z.coerce.boolean().nullable().transform(val => val ? 1 : 0).optional(),
  nValue_9: z.coerce.number().nullable().optional(),
  byScouterInfo_9: z.coerce.number().nullable().optional(),
});

export type ItemOptionFormData = z.infer<typeof itemOptionSchema>;

export const columns = [
  { key: 'tblidx', label: 'ID', type: 'number' as const, validation: itemOptionSchema.shape.tblidx },
  { key: 'wszOption_Name', label: 'Option Name', type: 'text' as const, validation: itemOptionSchema.shape.wszOption_Name },
  { key: 'bValidity_Able', label: 'Validity', type: 'boolean' as const, validation: itemOptionSchema.shape.bValidity_Able },
  { key: 'byOption_Rank', label: 'Option Rank', type: 'number' as const, validation: itemOptionSchema.shape.byOption_Rank },
  { key: 'byItem_Group', label: 'Item Group', type: 'number' as const, validation: itemOptionSchema.shape.byItem_Group },
  { key: 'byMaxQuality', label: 'Max Quality', type: 'number' as const, validation: itemOptionSchema.shape.byMaxQuality },
  { key: 'byQuality', label: 'Quality', type: 'number' as const, validation: itemOptionSchema.shape.byQuality },
  { key: 'byQualityIndex', label: 'Quality Index', type: 'number' as const, validation: itemOptionSchema.shape.byQualityIndex },
  { key: 'dwCost', label: 'Cost', type: 'number' as const, validation: itemOptionSchema.shape.dwCost },
  { key: 'byLevel', label: 'Level', type: 'number' as const, validation: itemOptionSchema.shape.byLevel },
  { key: 'activeEffect', label: 'Active Effect', type: 'number' as const, validation: itemOptionSchema.shape.activeEffect },
  { key: 'fActiveRate', label: 'Active Rate', type: 'number' as const, validation: itemOptionSchema.shape.fActiveRate },
  { key: 'szNote', label: 'Note', type: 'text' as const, validation: itemOptionSchema.shape.szNote },
  ...Array.from({ length: 10 }, (_, i) => [
    { key: `system_Effect_${i}`, label: `System Effect ${i}`, type: 'number' as const, validation: itemOptionSchema.shape[`system_Effect_${i}` as keyof typeof itemOptionSchema.shape] },
    { key: `bAppliedInPercent_${i}`, label: `Applied in Percent ${i}`, type: 'boolean' as const, validation: itemOptionSchema.shape[`bAppliedInPercent_${i}` as keyof typeof itemOptionSchema.shape] },
    { key: `nValue_${i}`, label: `Value ${i}`, type: 'number' as const, validation: itemOptionSchema.shape[`nValue_${i}` as keyof typeof itemOptionSchema.shape] },
    { key: `byScouterInfo_${i}`, label: `Scouter Info ${i}`, type: 'number' as const, validation: itemOptionSchema.shape[`byScouterInfo_${i}` as keyof typeof itemOptionSchema.shape] }
  ]).flat(),
];
