import { z } from 'zod';

// Define the schema for the item option table
export const itemOptionSchema = z.object({
  table_id: z.string().uuid().optional(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
  tblidx: z.number().optional(),
  wszoption_name: z.string().optional(),
  bvalidity_able: z.number().optional(),
  byoption_rank: z.number().optional(),
  byitem_group: z.number().optional(),
  bymaxquality: z.number().optional(),
  byquality: z.number().optional(),
  byqualityindex: z.number().optional(),
  dwcost: z.number().optional(),
  bylevel: z.number().optional(),
  activeeffect: z.number().optional(),
  factiverate: z.number().optional(),
  sznote: z.string().optional(),
  system_effect_0: z.string().optional(),
  bappliedinpercent_0: z.boolean().optional(),
  nvalue_0: z.number().optional(),
  byscouterinfo_0: z.number().optional(),
  system_effect_1: z.string().optional(),
  bappliedinpercent_1: z.boolean().optional(),
  nvalue_1: z.number().optional(),
  byscouterinfo_1: z.number().optional(),
  system_effect_2: z.string().optional(),
  bappliedinpercent_2: z.boolean().optional(),
  nvalue_2: z.number().optional(),
  byscouterinfo_2: z.number().optional(),
  system_effect_3: z.string().optional(),
  bappliedinpercent_3: z.boolean().optional(),
  nvalue_3: z.number().optional(),
  byscouterinfo_3: z.number().optional(),
}); 