import * as z from 'zod';

export const rankbattleTableSchema = z.object({
  table_id: z.string().uuid(),
  tblidx: z.coerce.number().min(0, 'Must be a positive number').max(9999999999, 'Cannot exceed 10 digits'),
  byRuleType: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  byBattleMode: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  byMatchType: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  wszName: z.string().nullable().transform(e => e === null ? "" : e),
  worldTblidx: z.coerce.number().min(0, 'Must be a positive number'),
  needItemTblidx: z.coerce.number().min(0, 'Must be a positive number'),
  dwZenny: z.coerce.number().min(0, 'Must be a positive number'),
  byMinLevel: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  byMaxLevel: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  byBattleCount: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  dwWaitTime: z.coerce.number().min(0, 'Must be a positive number'),
  dwDirectionTime: z.coerce.number().min(0, 'Must be a positive number'),
  dwMatchReadyTime: z.coerce.number().min(0, 'Must be a positive number'),
  dwStageReadyTime: z.coerce.number().min(0, 'Must be a positive number'),
  dwStageRunTime: z.coerce.number().min(0, 'Must be a positive number'),
  dwStageFinishTime: z.coerce.number().min(0, 'Must be a positive number'),
  dwMatchFinishTime: z.coerce.number().min(0, 'Must be a positive number'),
  dwBossDirectionTime: z.coerce.number().min(0, 'Must be a positive number'),
  dwBossKillTime: z.coerce.number().min(0, 'Must be a positive number'),
  dwBossEndingTime: z.coerce.number().min(0, 'Must be a positive number'),
  dwEndTime: z.coerce.number().min(0, 'Must be a positive number'),
  chScoreKO: z.coerce.number().min(-128, 'Must be within SMALLINT range').max(127, 'Cannot exceed SMALLINT max'),
  chScoreOutOfArea: z.coerce.number().min(-128, 'Must be within SMALLINT range').max(127, 'Cannot exceed SMALLINT max'),
  chScorePointWin: z.coerce.number().min(-128, 'Must be within SMALLINT range').max(127, 'Cannot exceed SMALLINT max'),
  chScoreDraw: z.coerce.number().min(-128, 'Must be within SMALLINT range').max(127, 'Cannot exceed SMALLINT max'),
  chScoreLose: z.coerce.number().min(-128, 'Must be within SMALLINT range').max(127, 'Cannot exceed SMALLINT max'),
  chResultExcellent: z.coerce.number().min(-128, 'Must be within SMALLINT range').max(127, 'Cannot exceed SMALLINT max'),
  chResultGreate: z.coerce.number().min(-128, 'Must be within SMALLINT range').max(127, 'Cannot exceed SMALLINT max'),
  chResultGood: z.coerce.number().min(-128, 'Must be within SMALLINT range').max(127, 'Cannot exceed SMALLINT max'),
  chResultDraw: z.coerce.number().min(-128, 'Must be within SMALLINT range').max(127, 'Cannot exceed SMALLINT max'),
  chResultLose: z.coerce.number().min(-128, 'Must be within SMALLINT range').max(127, 'Cannot exceed SMALLINT max'),
  chBonusPerfectWinner: z.coerce.number().min(-128, 'Must be within SMALLINT range').max(127, 'Cannot exceed SMALLINT max'),
  chBonusNormalWinner: z.coerce.number().min(-128, 'Must be within SMALLINT range').max(127, 'Cannot exceed SMALLINT max'),
  wszBGMName: z.string().nullable().transform(e => e === null ? "" : e),
  byDayEntryNum: z.coerce.number().min(0, 'Must be a positive number').max(32767, 'Cannot exceed SMALLINT max'),
  bOutSizeAble: z.coerce.boolean().transform(val => val ? 1 : 0),
  szCameraName: z.string().max(64, 'Cannot exceed 64 characters').nullable().transform(e => e === null ? "" : e),
  dwInfoIndex: z.coerce.number().min(0, 'Must be a positive number'),
  dwStateMinClearTime: z.coerce.number().min(0, 'Must be a positive number'),
});

export type RankbattleTableFormData = z.infer<typeof rankbattleTableSchema>;

export interface RankbattleTableRow extends RankbattleTableFormData {
  id: string;
}

export const columns = [
  { key: 'tblidx', label: 'Table ID', type: 'number' as const, validation: rankbattleTableSchema.shape.tblidx },
  { key: 'byRuleType', label: 'Rule Type', type: 'number' as const, validation: rankbattleTableSchema.shape.byRuleType },
  { key: 'byBattleMode', label: 'Battle Mode', type: 'number' as const, validation: rankbattleTableSchema.shape.byBattleMode },
  { key: 'byMatchType', label: 'Match Type', type: 'number' as const, validation: rankbattleTableSchema.shape.byMatchType },
  { key: 'wszName', label: 'Name', type: 'text' as const, validation: rankbattleTableSchema.shape.wszName },
  { key: 'worldTblidx', label: 'World Table ID', type: 'number' as const, validation: rankbattleTableSchema.shape.worldTblidx },
  { key: 'needItemTblidx', label: 'Need Item Table ID', type: 'number' as const, validation: rankbattleTableSchema.shape.needItemTblidx },
  { key: 'dwZenny', label: 'Zenny', type: 'number' as const, validation: rankbattleTableSchema.shape.dwZenny },
  { key: 'byMinLevel', label: 'Min Level', type: 'number' as const, validation: rankbattleTableSchema.shape.byMinLevel },
  { key: 'byMaxLevel', label: 'Max Level', type: 'number' as const, validation: rankbattleTableSchema.shape.byMaxLevel },
  { key: 'byBattleCount', label: 'Battle Count', type: 'number' as const, validation: rankbattleTableSchema.shape.byBattleCount },
  { key: 'dwWaitTime', label: 'Wait Time', type: 'number' as const, validation: rankbattleTableSchema.shape.dwWaitTime },
  { key: 'dwDirectionTime', label: 'Direction Time', type: 'number' as const, validation: rankbattleTableSchema.shape.dwDirectionTime },
  { key: 'dwMatchReadyTime', label: 'Match Ready Time', type: 'number' as const, validation: rankbattleTableSchema.shape.dwMatchReadyTime },
  { key: 'dwStageReadyTime', label: 'Stage Ready Time', type: 'number' as const, validation: rankbattleTableSchema.shape.dwStageReadyTime },
  { key: 'dwStageRunTime', label: 'Stage Run Time', type: 'number' as const, validation: rankbattleTableSchema.shape.dwStageRunTime },
  { key: 'dwStageFinishTime', label: 'Stage Finish Time', type: 'number' as const, validation: rankbattleTableSchema.shape.dwStageFinishTime },
  { key: 'dwMatchFinishTime', label: 'Match Finish Time', type: 'number' as const, validation: rankbattleTableSchema.shape.dwMatchFinishTime },
  { key: 'dwBossDirectionTime', label: 'Boss Direction Time', type: 'number' as const, validation: rankbattleTableSchema.shape.dwBossDirectionTime },
  { key: 'dwBossKillTime', label: 'Boss Kill Time', type: 'number' as const, validation: rankbattleTableSchema.shape.dwBossKillTime },
  { key: 'dwBossEndingTime', label: 'Boss Ending Time', type: 'number' as const, validation: rankbattleTableSchema.shape.dwBossEndingTime },
  { key: 'dwEndTime', label: 'End Time', type: 'number' as const, validation: rankbattleTableSchema.shape.dwEndTime },
  { key: 'chScoreKO', label: 'Score KO', type: 'number' as const, validation: rankbattleTableSchema.shape.chScoreKO },
  { key: 'chScoreOutOfArea', label: 'Score Out Of Area', type: 'number' as const, validation: rankbattleTableSchema.shape.chScoreOutOfArea },
  { key: 'chScorePointWin', label: 'Score Point Win', type: 'number' as const, validation: rankbattleTableSchema.shape.chScorePointWin },
  { key: 'chScoreDraw', label: 'Score Draw', type: 'number' as const, validation: rankbattleTableSchema.shape.chScoreDraw },
  { key: 'chScoreLose', label: 'Score Lose', type: 'number' as const, validation: rankbattleTableSchema.shape.chScoreLose },
  { key: 'chResultExcellent', label: 'Result Excellent', type: 'number' as const, validation: rankbattleTableSchema.shape.chResultExcellent },
  { key: 'chResultGreate', label: 'Result Great', type: 'number' as const, validation: rankbattleTableSchema.shape.chResultGreate },
  { key: 'chResultGood', label: 'Result Good', type: 'number' as const, validation: rankbattleTableSchema.shape.chResultGood },
  { key: 'chResultDraw', label: 'Result Draw', type: 'number' as const, validation: rankbattleTableSchema.shape.chResultDraw },
  { key: 'chResultLose', label: 'Result Lose', type: 'number' as const, validation: rankbattleTableSchema.shape.chResultLose },
  { key: 'chBonusPerfectWinner', label: 'Bonus Perfect Winner', type: 'number' as const, validation: rankbattleTableSchema.shape.chBonusPerfectWinner },
  { key: 'chBonusNormalWinner', label: 'Bonus Normal Winner', type: 'number' as const, validation: rankbattleTableSchema.shape.chBonusNormalWinner },
  { key: 'wszBGMName', label: 'BGM Name', type: 'text' as const, validation: rankbattleTableSchema.shape.wszBGMName },
  { key: 'byDayEntryNum', label: 'Day Entry Num', type: 'number' as const, validation: rankbattleTableSchema.shape.byDayEntryNum },
  { key: 'bOutSizeAble', label: 'Out Size Able', type: 'boolean' as const, validation: rankbattleTableSchema.shape.bOutSizeAble },
  { key: 'szCameraName', label: 'Camera Name', type: 'text' as const, validation: rankbattleTableSchema.shape.szCameraName },
  { key: 'dwInfoIndex', label: 'Info Index', type: 'number' as const, validation: rankbattleTableSchema.shape.dwInfoIndex },
  { key: 'dwStateMinClearTime', label: 'State Min Clear Time', type: 'number' as const, validation: rankbattleTableSchema.shape.dwStateMinClearTime },
];

