import { z } from "zod";

// Define the schema for the mob table
export const mobSchema = z.object({
  table_id: z.string().uuid().optional(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
  tblidx: z.number().optional(),
  bValidity_Able: z.coerce.boolean().optional().transform(val => val ? 1 : 0),
  Name: z.number().optional(),
  wszNameText: z.string().nullable().transform(e => e === null ? "" : e).optional(),
  szModel: z.string().nullable().transform(e => e === null ? "" : e).optional(),
  byLevel: z.number().optional(),
  byGrade: z.number().optional(),
  dwAi_Bit_Flag: z.number().optional(),
  wLP_Regeneration: z.number().optional(),
  wEP_Regeneration: z.number().optional(),
  byAttack_Animation_Quantity: z.number().optional(),
  byBattle_Attribute: z.number().optional(),
  wBasic_Physical_Offence: z.number().optional(),
  wBasic_Energy_Offence: z.number().optional(),
  fWalk_Speed_Origin: z.number().optional(),
  fWalk_Speed: z.number().optional(),
  fRun_Speed_Origin: z.number().optional(),
  fRun_Speed: z.number().optional(),
  fRadius_X: z.number().optional(),
  fRadius_Z: z.number().optional(),
  wSight_Range: z.number().optional(),
  wScan_Range: z.number().optional(),
  byVisible_Sight_Range: z.number().optional(),
  szCamera_Bone_Name: z.string().nullable().transform(e => e === null ? "" : e).optional(),
  wAttackCoolTime: z.number().optional(),
  fFly_Height: z.number().optional(),
  szNameText: z.string().nullable().transform(e => e === null ? "" : e).optional(),
  bSpawn_Animation: z.coerce.boolean().optional().transform(val => val ? 1 : 0),
  dwDialogGroup: z.number().optional(),
  szILLust: z.string().nullable().transform(e => e === null ? "" : e).optional(),
  dwAllianceIdx: z.number().optional(),
  wAggroMaxCount: z.number().optional(),
  dwNpcAttributeFlag: z.number().optional(),
  wStomachacheDefence: z.number().optional(),
  wPoisonDefence: z.number().optional(),
  wBleedDefence: z.number().optional(),
  wBurnDefence: z.number().optional(),
  dwBasic_LP: z.number().optional(),
  wBasic_EP: z.number().optional(),
  wBasic_Physical_Defence: z.number().optional(),
  wBasic_Energy_Defence: z.number().optional(),
  wBasicStr: z.number().optional(),
  wBasicCon: z.number().optional(),
  wBasicFoc: z.number().optional(),
  wBasicDex: z.number().optional(),
  wBasicSol: z.number().optional(),
  wBasicEng: z.number().optional(),
  fScale: z.number().optional(),
  wAttack_Speed_Rate: z.number().optional(),
  byAttack_Type: z.number().optional(),
  fAttack_Range: z.number().optional(),
  wAttack_Rate: z.number().optional(),
  wDodge_Rate: z.number().optional(),
  wBlock_Rate: z.number().optional(),
  wCurse_Success_Rate: z.number().optional(),
  wCurse_Tolerance_Rate: z.number().optional(),
  fRadius: z.number().optional(),
  wBasic_Aggro_Point: z.number().optional(),
  dwMobGroup: z.number().optional(),
  wMob_Kind: z.number().optional(),
  dwDrop_Zenny: z.number().optional(),
  fDrop_Zenny_Rate: z.number().optional(),
  dwExp: z.number().optional(),
  byMob_Type: z.number().optional(),
  drop_Item_Tblidx: z.number().optional(),
  bSize: z.coerce.boolean().optional().transform(val => val ? 1 : 0),
  wTMQPoint: z.number().optional(),
  dropQuestTblidx: z.number().optional(),
  idxBigBag1: z.number().optional(),
  byDropRate1: z.number().optional(),
  byTryCount1: z.number().optional(),
  idxBigBag2: z.number().optional(),
  byDropRate2: z.number().optional(),
  byTryCount2: z.number().optional(),
  idxBigBag3: z.number().optional(),
  byDropRate3: z.number().optional(),
  byTryCount3: z.number().optional(),
  dwUnknown: z.number().optional(),
  byUnknown: z.number().optional(),
  byUnknown2: z.number().optional(),
  bShow_Name: z.coerce.boolean().optional().transform(val => val ? 1 : 0),
  wSightAngle: z.number().optional(),
  dwImmunity_Bit_Flag: z.number().optional(),
  bIsDragonBallDrop: z.coerce.boolean().optional().transform(val => val ? 1 : 0),
  wMonsterClass: z.number().optional(),
  wUseRace: z.number().optional(),
  fRewardExpRate: z.number().optional(),
  fRewardZennyRate: z.number().optional(),
  dwFormulaOffset: z.number().optional(),
  fSettingRate_LP: z.number().optional(),
  fSettingRate_LPRegen: z.number().optional(),
  fSettingRate_PhyOffence: z.number().optional(),
  fSettingRate_EngOffence: z.number().optional(),
  fSettingRate_PhyDefence: z.number().optional(),
  fSettingRate_EngDefence: z.number().optional(),
  fSettingRate_AttackRate: z.number().optional(),
  fSettingRate_DodgeRate: z.number().optional(),
  fSettingPhyOffenceRate: z.number().optional(),
  fSettingEngOffenceRate: z.number().optional(),
  fSettingRate_Defence_Role: z.number().optional(),
  wUse_Skill_Time_0: z.number().optional(),
  use_Skill_Tblidx_0: z.number().optional(),
  byUse_Skill_Basis_0: z.number().optional(),
  wUse_Skill_LP_0: z.number().optional(),
  wUse_Skill_Time_1: z.number().optional(),
  use_Skill_Tblidx_1: z.number().optional(),
  byUse_Skill_Basis_1: z.number().optional(),
  wUse_Skill_LP_1: z.number().optional(),
  wUse_Skill_Time_2: z.number().optional(),
  use_Skill_Tblidx_2: z.number().optional(),
  byUse_Skill_Basis_2: z.number().optional(),
  wUse_Skill_LP_2: z.number().optional(),
  wUse_Skill_Time_3: z.number().optional(),
  use_Skill_Tblidx_3: z.number().optional(),
  byUse_Skill_Basis_3: z.number().optional(),
  wUse_Skill_LP_3: z.number().optional(),
  wUse_Skill_Time_4: z.number().optional(),
  use_Skill_Tblidx_4: z.number().optional(),
  byUse_Skill_Basis_4: z.number().optional(),
  wUse_Skill_LP_4: z.number().optional(),
  wUse_Skill_Time_5: z.number().optional(),
  use_Skill_Tblidx_5: z.number().optional(),
  byUse_Skill_Basis_5: z.number().optional(),
  wUse_Skill_LP_5: z.number().optional(),
  wUse_Skill_Time_6: z.number().optional(),
  use_Skill_Tblidx_6: z.number().optional(),
  byUse_Skill_Basis_6: z.number().optional(),
  wUse_Skill_LP_6: z.number().optional(),
  wUse_Skill_Time_7: z.number().optional(),
  use_Skill_Tblidx_7: z.number().optional(),
  byUse_Skill_Basis_7: z.number().optional(),
  wUse_Skill_LP_7: z.number().optional(),
  wUse_Skill_Time_8: z.number().optional(),
  use_Skill_Tblidx_8: z.number().optional(),
  byUse_Skill_Basis_8: z.number().optional(),
  wUse_Skill_LP_8: z.number().optional(),
  wUse_Skill_Time_9: z.number().optional(),
  use_Skill_Tblidx_9: z.number().optional(),
  byUse_Skill_Basis_9: z.number().optional(),
  wUse_Skill_LP_9: z.number().optional(),
});

export type MobFormData = z.infer<typeof mobSchema>;

export const columns = [
  { key: 'tblidx', label: 'ID', type: 'number' as const, validation: mobSchema.shape.tblidx },
  { key: 'Name', label: 'Name', type: 'number' as const, validation: mobSchema.shape.Name },
  { key: 'wszNameText', label: 'Display Name', type: 'text' as const, validation: mobSchema.shape.wszNameText },
  { key: 'szModel', label: 'Model', type: 'text' as const, validation: mobSchema.shape.szModel },
  { key: 'byLevel', label: 'Level', type: 'number' as const, validation: mobSchema.shape.byLevel },
  { key: 'byGrade', label: 'Grade', type: 'number' as const, validation: mobSchema.shape.byGrade },
  { key: 'bValidity_Able', label: 'Valid', type: 'boolean' as const, validation: mobSchema.shape.bValidity_Able },
  { key: 'dwBasic_LP', label: 'Base LP', type: 'number' as const, validation: mobSchema.shape.dwBasic_LP },
  { key: 'wBasic_EP', label: 'Base EP', type: 'number' as const, validation: mobSchema.shape.wBasic_EP },
  { key: 'wBasic_Physical_Offence', label: 'Physical Attack', type: 'number' as const, validation: mobSchema.shape.wBasic_Physical_Offence },
  { key: 'wBasic_Energy_Offence', label: 'Energy Attack', type: 'number' as const, validation: mobSchema.shape.wBasic_Energy_Offence },
  { key: 'wBasic_Physical_Defence', label: 'Physical Defense', type: 'number' as const, validation: mobSchema.shape.wBasic_Physical_Defence },
  { key: 'wBasic_Energy_Defence', label: 'Energy Defense', type: 'number' as const, validation: mobSchema.shape.wBasic_Energy_Defence },
  { key: 'wBasicStr', label: 'STR', type: 'number' as const, validation: mobSchema.shape.wBasicStr },
  { key: 'wBasicCon', label: 'CON', type: 'number' as const, validation: mobSchema.shape.wBasicCon },
  { key: 'wBasicFoc', label: 'FOC', type: 'number' as const, validation: mobSchema.shape.wBasicFoc },
  { key: 'wBasicDex', label: 'DEX', type: 'number' as const, validation: mobSchema.shape.wBasicDex },
  { key: 'wBasicSol', label: 'SOL', type: 'number' as const, validation: mobSchema.shape.wBasicSol },
  { key: 'wBasicEng', label: 'ENG', type: 'number' as const, validation: mobSchema.shape.wBasicEng },
  { key: 'dwAi_Bit_Flag', label: 'AI Bit Flag', type: 'number' as const, validation: mobSchema.shape.dwAi_Bit_Flag },
  { key: 'wLP_Regeneration', label: 'LP Regen', type: 'number' as const, validation: mobSchema.shape.wLP_Regeneration },
  { key: 'wEP_Regeneration', label: 'EP Regen', type: 'number' as const, validation: mobSchema.shape.wEP_Regeneration },
  { key: 'byAttack_Animation_Quantity', label: 'Attack Animation Quantity', type: 'number' as const, validation: mobSchema.shape.byAttack_Animation_Quantity },
  { key: 'byBattle_Attribute', label: 'Battle Attribute', type: 'number' as const, validation: mobSchema.shape.byBattle_Attribute },
  { key: 'fWalk_Speed_Origin', label: 'Base Walk Speed', type: 'number' as const, validation: mobSchema.shape.fWalk_Speed_Origin },
  { key: 'fWalk_Speed', label: 'Walk Speed', type: 'number' as const, validation: mobSchema.shape.fWalk_Speed },
  { key: 'fRun_Speed_Origin', label: 'Base Run Speed', type: 'number' as const, validation: mobSchema.shape.fRun_Speed_Origin },
  { key: 'fRun_Speed', label: 'Run Speed', type: 'number' as const, validation: mobSchema.shape.fRun_Speed },
  { key: 'fRadius_X', label: 'Radius X', type: 'number' as const, validation: mobSchema.shape.fRadius_X },
  { key: 'fRadius_Z', label: 'Radius Z', type: 'number' as const, validation: mobSchema.shape.fRadius_Z },
  { key: 'wSight_Range', label: 'Sight Range', type: 'number' as const, validation: mobSchema.shape.wSight_Range },
  { key: 'wScan_Range', label: 'Scan Range', type: 'number' as const, validation: mobSchema.shape.wScan_Range },
  { key: 'byVisible_Sight_Range', label: 'Visible Sight Range', type: 'number' as const, validation: mobSchema.shape.byVisible_Sight_Range },
  { key: 'szCamera_Bone_Name', label: 'Camera Bone', type: 'text' as const, validation: mobSchema.shape.szCamera_Bone_Name },
  { key: 'wAttackCoolTime', label: 'Attack Cooldown', type: 'number' as const, validation: mobSchema.shape.wAttackCoolTime },
  { key: 'fFly_Height', label: 'Fly Height', type: 'number' as const, validation: mobSchema.shape.fFly_Height },
  { key: 'szNameText', label: 'Display Name', type: 'text' as const, validation: mobSchema.shape.szNameText },
  { key: 'bSpawn_Animation', label: 'Spawn Animation', type: 'boolean' as const, validation: mobSchema.shape.bSpawn_Animation },
  { key: 'dwDialogGroup', label: 'Dialog Group', type: 'number' as const, validation: mobSchema.shape.dwDialogGroup },
  { key: 'szILLust', label: 'Illustration', type: 'text' as const, validation: mobSchema.shape.szILLust },
  { key: 'dwAllianceIdx', label: 'Alliance Index', type: 'number' as const, validation: mobSchema.shape.dwAllianceIdx },
  { key: 'wAggroMaxCount', label: 'Max Aggro Count', type: 'number' as const, validation: mobSchema.shape.wAggroMaxCount },
  { key: 'dwNpcAttributeFlag', label: 'NPC Attribute Flag', type: 'number' as const, validation: mobSchema.shape.dwNpcAttributeFlag },
  { key: 'wStomachacheDefence', label: 'Stomachache Defense', type: 'number' as const, validation: mobSchema.shape.wStomachacheDefence },
  { key: 'wPoisonDefence', label: 'Poison Defense', type: 'number' as const, validation: mobSchema.shape.wPoisonDefence },
  { key: 'wBleedDefence', label: 'Bleed Defense', type: 'number' as const, validation: mobSchema.shape.wBleedDefence },
  { key: 'wBurnDefence', label: 'Burn Defense', type: 'number' as const, validation: mobSchema.shape.wBurnDefence },
  { key: 'fScale', label: 'Scale', type: 'number' as const, validation: mobSchema.shape.fScale },
  { key: 'wAttack_Speed_Rate', label: 'Attack Speed Rate', type: 'number' as const, validation: mobSchema.shape.wAttack_Speed_Rate },
  { key: 'byAttack_Type', label: 'Attack Type', type: 'number' as const, validation: mobSchema.shape.byAttack_Type },
  { key: 'fAttack_Range', label: 'Attack Range', type: 'number' as const, validation: mobSchema.shape.fAttack_Range },
  { key: 'wAttack_Rate', label: 'Attack Rate', type: 'number' as const, validation: mobSchema.shape.wAttack_Rate },
  { key: 'wDodge_Rate', label: 'Dodge Rate', type: 'number' as const, validation: mobSchema.shape.wDodge_Rate },
  { key: 'wBlock_Rate', label: 'Block Rate', type: 'number' as const, validation: mobSchema.shape.wBlock_Rate },
  { key: 'wCurse_Success_Rate', label: 'Curse Success Rate', type: 'number' as const, validation: mobSchema.shape.wCurse_Success_Rate },
  { key: 'wCurse_Tolerance_Rate', label: 'Curse Tolerance Rate', type: 'number' as const, validation: mobSchema.shape.wCurse_Tolerance_Rate },
  { key: 'fRadius', label: 'Radius', type: 'number' as const, validation: mobSchema.shape.fRadius },
  { key: 'wBasic_Aggro_Point', label: 'Base Aggro Point', type: 'number' as const, validation: mobSchema.shape.wBasic_Aggro_Point },
  { key: 'dwMobGroup', label: 'Mob Group', type: 'number' as const, validation: mobSchema.shape.dwMobGroup },
  { key: 'wMob_Kind', label: 'Mob Kind', type: 'number' as const, validation: mobSchema.shape.wMob_Kind },
  { key: 'dwDrop_Zenny', label: 'Drop Zenny', type: 'number' as const, validation: mobSchema.shape.dwDrop_Zenny },
  { key: 'fDrop_Zenny_Rate', label: 'Drop Zenny Rate', type: 'number' as const, validation: mobSchema.shape.fDrop_Zenny_Rate },
  { key: 'dwExp', label: 'EXP', type: 'number' as const, validation: mobSchema.shape.dwExp },
  { key: 'byMob_Type', label: 'Mob Type', type: 'number' as const, validation: mobSchema.shape.byMob_Type },
  { key: 'drop_Item_Tblidx', label: 'Drop Item ID', type: 'number' as const, validation: mobSchema.shape.drop_Item_Tblidx },
  { key: 'bSize', label: 'Size', type: 'boolean' as const, validation: mobSchema.shape.bSize },
  { key: 'wTMQPoint', label: 'TMQ Point', type: 'number' as const, validation: mobSchema.shape.wTMQPoint },
  { key: 'dropQuestTblidx', label: 'Drop Quest ID', type: 'number' as const, validation: mobSchema.shape.dropQuestTblidx },
  { key: 'idxBigBag1', label: 'Big Bag 1', type: 'number' as const, validation: mobSchema.shape.idxBigBag1 },
  { key: 'byDropRate1', label: 'Drop Rate 1', type: 'number' as const, validation: mobSchema.shape.byDropRate1 },
  { key: 'byTryCount1', label: 'Try Count 1', type: 'number' as const, validation: mobSchema.shape.byTryCount1 },
  { key: 'idxBigBag2', label: 'Big Bag 2', type: 'number' as const, validation: mobSchema.shape.idxBigBag2 },
  { key: 'byDropRate2', label: 'Drop Rate 2', type: 'number' as const, validation: mobSchema.shape.byDropRate2 },
  { key: 'byTryCount2', label: 'Try Count 2', type: 'number' as const, validation: mobSchema.shape.byTryCount2 },
  { key: 'idxBigBag3', label: 'Big Bag 3', type: 'number' as const, validation: mobSchema.shape.idxBigBag3 },
  { key: 'byDropRate3', label: 'Drop Rate 3', type: 'number' as const, validation: mobSchema.shape.byDropRate3 },
  { key: 'byTryCount3', label: 'Try Count 3', type: 'number' as const, validation: mobSchema.shape.byTryCount3 },
  { key: 'dwUnknown', label: 'Unknown', type: 'number' as const, validation: mobSchema.shape.dwUnknown },
  { key: 'byUnknown', label: 'Unknown', type: 'number' as const, validation: mobSchema.shape.byUnknown },
  { key: 'byUnknown2', label: 'Unknown 2', type: 'number' as const, validation: mobSchema.shape.byUnknown2 },
  { key: 'bShow_Name', label: 'Show Name', type: 'boolean' as const, validation: mobSchema.shape.bShow_Name },
  { key: 'wSightAngle', label: 'Sight Angle', type: 'number' as const, validation: mobSchema.shape.wSightAngle },
  { key: 'dwImmunity_Bit_Flag', label: 'Immunity Bit Flag', type: 'number' as const, validation: mobSchema.shape.dwImmunity_Bit_Flag },
  { key: 'bIsDragonBallDrop', label: 'Is Dragon Ball Drop', type: 'boolean' as const, validation: mobSchema.shape.bIsDragonBallDrop },
  { key: 'wMonsterClass', label: 'Monster Class', type: 'number' as const, validation: mobSchema.shape.wMonsterClass },
  { key: 'wUseRace', label: 'User Race', type: 'number' as const, validation: mobSchema.shape.wUseRace },
  { key: 'fRewardExpRate', label: 'Reward EXP Rate', type: 'number' as const, validation: mobSchema.shape.fRewardExpRate },
  { key: 'fRewardZennyRate', label: 'Reward Zenny Rate', type: 'number' as const, validation: mobSchema.shape.fRewardZennyRate },
  { key: 'dwFormulaOffset', label: 'Formula Offset', type: 'number' as const, validation: mobSchema.shape.dwFormulaOffset },
  { key: 'fSettingRate_LP', label: 'Setting Rate LP', type: 'number' as const, validation: mobSchema.shape.fSettingRate_LP },
  { key: 'fSettingRate_LPRegen', label: 'Setting Rate LP Regen', type: 'number' as const, validation: mobSchema.shape.fSettingRate_LPRegen },
  { key: 'fSettingRate_PhyOffence', label: 'Setting Rate Physical Offence', type: 'number' as const, validation: mobSchema.shape.fSettingRate_PhyOffence },
  { key: 'fSettingRate_EngOffence', label: 'Setting Rate Energy Offence', type: 'number' as const, validation: mobSchema.shape.fSettingRate_EngOffence },
  { key: 'fSettingRate_PhyDefence', label: 'Setting Rate Physical Defence', type: 'number' as const, validation: mobSchema.shape.fSettingRate_PhyDefence },
  { key: 'fSettingRate_EngDefence', label: 'Setting Rate Energy Defence', type: 'number' as const, validation: mobSchema.shape.fSettingRate_EngDefence },
  { key: 'fSettingRate_AttackRate', label: 'Setting Rate Attack Rate', type: 'number' as const, validation: mobSchema.shape.fSettingRate_AttackRate },
  { key: 'fSettingRate_DodgeRate', label: 'Setting Rate Dodge Rate', type: 'number' as const, validation: mobSchema.shape.fSettingRate_DodgeRate },
  { key: 'fSettingPhyOffenceRate', label: 'Setting Physical Offence Rate', type: 'number' as const, validation: mobSchema.shape.fSettingPhyOffenceRate },
  { key: 'fSettingEngOffenceRate', label: 'Setting Energy Offence Rate', type: 'number' as const, validation: mobSchema.shape.fSettingEngOffenceRate },
  { key: 'fSettingRate_Defence_Role', label: 'Setting Rate Defence Role', type: 'number' as const, validation: mobSchema.shape.fSettingRate_Defence_Role },
  ...Array.from({ length: 10 }, (i) => [
    { key: `wUse_Skill_Time_${i}`, label: `Skill ${i} Time`, type: 'number' as const, validation: mobSchema.shape[`wUse_Skill_Time_${i}` as keyof typeof mobSchema.shape] },
    { key: `use_Skill_Tblidx_${i}`, label: `Skill ${i} Index`, type: 'number' as const, validation: mobSchema.shape[`use_Skill_Tblidx_${i}` as keyof typeof mobSchema.shape] },
    { key: `byUse_Skill_Basis_${i}`, label: `Skill ${i} Basis`, type: 'number' as const, validation: mobSchema.shape[`byUse_Skill_Basis_${i}` as keyof typeof mobSchema.shape] },
    { key: `wUse_Skill_LP_${i}`, label: `Skill ${i} LP`, type: 'number' as const, validation: mobSchema.shape[`wUse_Skill_LP_${i}` as keyof typeof mobSchema.shape] }
  ]).flat(),
];
