import { z } from "zod";

// Define the schema for the mob table
export const mobSchema = z.object({
  table_id: z.string().uuid().optional(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
  tblidx: z.number().optional(),
  bvalidity_able: z.boolean().optional(),
  name: z.string().optional(),
  wsznametext: z.string().optional(),
  szmodel: z.string().optional(),
  bylevel: z.number().optional(),
  bygrade: z.number().optional(),
  dwai_bit_flag: z.number().optional(),
  wlp_regeneration: z.number().optional(),
  wep_regeneration: z.number().optional(),
  byattack_animation_quantity: z.number().optional(),
  bybattle_attribute: z.number().optional(),
  wbasic_physical_offence: z.number().optional(),
  wbasic_energy_offence: z.number().optional(),
  fwalk_speed_origin: z.number().optional(),
  fwalk_speed: z.number().optional(),
  frun_speed_origin: z.number().optional(),
  frun_speed: z.number().optional(),
  fradius_x: z.number().optional(),
  fradius_z: z.number().optional(),
  wsight_range: z.number().optional(),
  wscan_range: z.number().optional(),
  byvisible_sight_range: z.number().optional(),
  szcamera_bone_name: z.string().optional(),
  wattackcooltime: z.number().optional(),
  ffly_height: z.number().optional(),
  sznametext: z.string().optional(),
  bspawn_animation: z.boolean().optional(),
  dwdialoggroup: z.number().optional(),
  szillust: z.string().optional(),
  dwallianceidx: z.number().optional(),
  waggromaxcount: z.number().optional(),
  dwnpcattributeflag: z.number().optional(),
  wstomachachedefence: z.number().optional(),
  wpoisondefence: z.number().optional(),
  wbleeddefence: z.number().optional(),
  wburndefence: z.number().optional(),
  dwbasic_lp: z.number().optional(),
  wbasic_ep: z.number().optional(),
  wbasic_physical_defence: z.number().optional(),
  wbasic_energy_defence: z.number().optional(),
  wbasicstr: z.number().optional(),
  wbasiccon: z.number().optional(),
  wbasicfoc: z.number().optional(),
  wbasicdex: z.number().optional(),
  wbasicsol: z.number().optional(),
  wbasiceng: z.number().optional(),
  fscale: z.number().optional(),
  wattack_speed_rate: z.number().optional(),
  byattack_type: z.number().optional(),
  fattack_range: z.number().optional(),
  wattack_rate: z.number().optional(),
  wdodge_rate: z.number().optional(),
  wblock_rate: z.number().optional(),
  wcurse_success_rate: z.number().optional(),
  wcurse_tolerance_rate: z.number().optional(),
  fradius: z.number().optional(),
  wbasic_aggro_point: z.number().optional(),
  dwmobgroup: z.number().optional(),
  wmob_kind: z.number().optional(),
  dwdrop_zenny: z.number().optional(),
  fdrop_zenny_rate: z.number().optional(),
  dwexp: z.number().optional(),
  bymob_type: z.number().optional(),
  drop_item_tblidx: z.number().optional(),
  bsize: z.boolean().optional(),
  wtmqpoint: z.number().optional(),
  dropquesttblidx: z.number().optional(),
  idxbigbag1: z.number().optional(),
  bydroprate1: z.number().optional(),
  bytrycount1: z.number().optional(),
  idxbigbag2: z.number().optional(),
  bydroprate2: z.number().optional(),
  bytrycount2: z.number().optional(),
  idxbigbag3: z.number().optional(),
  bydroprate3: z.number().optional(),
  bytrycount3: z.number().optional(),
  dwunknown: z.number().optional(),
  byunknown: z.number().optional(),
  byunknown2: z.number().optional(),
  bshow_name: z.boolean().optional(),
  wsightangle: z.number().optional(),
  dwimmunity_bit_flag: z.number().optional(),
  bisdragonballdrop: z.boolean().optional(),
  wmonsterclass: z.number().optional(),
  wuserace: z.number().optional(),
  frewardexprate: z.number().optional(),
  frewardzennyrate: z.number().optional(),
  dwformulaoffset: z.number().optional(),
  fsettingrate_lp: z.number().optional(),
  fsettingrate_lpregen: z.number().optional(),
  fsettingrate_phyoffence: z.number().optional(),
  fsettingrate_engoffence: z.number().optional(),
  fsettingrate_phydefence: z.number().optional(),
  fsettingrate_engdefence: z.number().optional(),
  fsettingrate_attackrate: z.number().optional(),
  fsettingrate_dodgerate: z.number().optional(),
  fsettingphyoffencerate: z.number().optional(),
  fsettingengoffencerate: z.number().optional(),
  fsettingrate_defence_role: z.number().optional(),
  wuse_skill_time_0: z.number().optional(),
  use_skill_tblidx_0: z.number().optional(),
  byuse_skill_basis_0: z.number().optional(),
  wuse_skill_lp_0: z.number().optional(),
  wuse_skill_time_1: z.number().optional(),
  use_skill_tblidx_1: z.number().optional(),
  byuse_skill_basis_1: z.number().optional(),
  wuse_skill_lp_1: z.number().optional(),
  wuse_skill_time_2: z.number().optional(),
  use_skill_tblidx_2: z.number().optional(),
  byuse_skill_basis_2: z.number().optional(),
  wuse_skill_lp_2: z.number().optional(),
  wuse_skill_time_3: z.number().optional(),
  use_skill_tblidx_3: z.number().optional(),
  byuse_skill_basis_3: z.number().optional(),
  wuse_skill_lp_3: z.number().optional(),
  wuse_skill_time_4: z.number().optional(),
  use_skill_tblidx_4: z.number().optional(),
  byuse_skill_basis_4: z.number().optional(),
  wuse_skill_lp_4: z.number().optional(),
  wuse_skill_time_5: z.number().optional(),
  use_skill_tblidx_5: z.number().optional(),
  byuse_skill_basis_5: z.number().optional(),
  wuse_skill_lp_5: z.number().optional(),
  wuse_skill_time_6: z.number().optional(),
  use_skill_tblidx_6: z.number().optional(),
  byuse_skill_basis_6: z.number().optional(),
  wuse_skill_lp_6: z.number().optional(),
});

export type MobFormData = z.infer<typeof mobSchema>;

export const columns = [
  { key: 'tblidx', label: 'ID', type: 'number' as const, validation: mobSchema.shape.tblidx },
  { key: 'name', label: 'Name', type: 'text' as const, validation: mobSchema.shape.name },
  { key: 'wsznametext', label: 'Display Name', type: 'text' as const, validation: mobSchema.shape.wsznametext },
  { key: 'szmodel', label: 'Model', type: 'text' as const, validation: mobSchema.shape.szmodel },
  { key: 'bylevel', label: 'Level', type: 'number' as const, validation: mobSchema.shape.bylevel },
  { key: 'bygrade', label: 'Grade', type: 'number' as const, validation: mobSchema.shape.bygrade },
  { key: 'bvalidity_able', label: 'Valid', type: 'boolean' as const, validation: mobSchema.shape.bvalidity_able },
  { key: 'dwbasic_lp', label: 'Base LP', type: 'number' as const, validation: mobSchema.shape.dwbasic_lp },
  { key: 'wbasic_ep', label: 'Base EP', type: 'number' as const, validation: mobSchema.shape.wbasic_ep },
  { key: 'wbasic_physical_offence', label: 'Physical Attack', type: 'number' as const, validation: mobSchema.shape.wbasic_physical_offence },
  { key: 'wbasic_energy_offence', label: 'Energy Attack', type: 'number' as const, validation: mobSchema.shape.wbasic_energy_offence },
  { key: 'wbasic_physical_defence', label: 'Physical Defense', type: 'number' as const, validation: mobSchema.shape.wbasic_physical_defence },
  { key: 'wbasic_energy_defence', label: 'Energy Defense', type: 'number' as const, validation: mobSchema.shape.wbasic_energy_defence },
  { key: 'wbasicstr', label: 'STR', type: 'number' as const, validation: mobSchema.shape.wbasicstr },
  { key: 'wbasiccon', label: 'CON', type: 'number' as const, validation: mobSchema.shape.wbasiccon },
  { key: 'wbasicfoc', label: 'FOC', type: 'number' as const, validation: mobSchema.shape.wbasicfoc },
  { key: 'wbasicdex', label: 'DEX', type: 'number' as const, validation: mobSchema.shape.wbasicdex },
  { key: 'wbasicsol', label: 'SOL', type: 'number' as const, validation: mobSchema.shape.wbasicsol },
  { key: 'wbasiceng', label: 'ENG', type: 'number' as const, validation: mobSchema.shape.wbasiceng },
  { key: 'dwai_bit_flag', label: 'AI Bit Flag', type: 'number' as const, validation: mobSchema.shape.dwai_bit_flag },
  { key: 'wlp_regeneration', label: 'LP Regen', type: 'number' as const, validation: mobSchema.shape.wlp_regeneration },
  { key: 'wep_regeneration', label: 'EP Regen', type: 'number' as const, validation: mobSchema.shape.wep_regeneration },
  { key: 'byattack_animation_quantity', label: 'Attack Animation Quantity', type: 'number' as const, validation: mobSchema.shape.byattack_animation_quantity },
  { key: 'bybattle_attribute', label: 'Battle Attribute', type: 'number' as const, validation: mobSchema.shape.bybattle_attribute },
  { key: 'fwalk_speed_origin', label: 'Base Walk Speed', type: 'number' as const, validation: mobSchema.shape.fwalk_speed_origin },
  { key: 'fwalk_speed', label: 'Walk Speed', type: 'number' as const, validation: mobSchema.shape.fwalk_speed },
  { key: 'frun_speed_origin', label: 'Base Run Speed', type: 'number' as const, validation: mobSchema.shape.frun_speed_origin },
  { key: 'frun_speed', label: 'Run Speed', type: 'number' as const, validation: mobSchema.shape.frun_speed },
  { key: 'fradius_x', label: 'Radius X', type: 'number' as const, validation: mobSchema.shape.fradius_x },
  { key: 'fradius_z', label: 'Radius Z', type: 'number' as const, validation: mobSchema.shape.fradius_z },
  { key: 'wsight_range', label: 'Sight Range', type: 'number' as const, validation: mobSchema.shape.wsight_range },
  { key: 'wscan_range', label: 'Scan Range', type: 'number' as const, validation: mobSchema.shape.wscan_range },
  { key: 'byvisible_sight_range', label: 'Visible Sight Range', type: 'number' as const, validation: mobSchema.shape.byvisible_sight_range },
  { key: 'szcamera_bone_name', label: 'Camera Bone', type: 'text' as const, validation: mobSchema.shape.szcamera_bone_name },
  { key: 'wattackcooltime', label: 'Attack Cooldown', type: 'number' as const, validation: mobSchema.shape.wattackcooltime },
  { key: 'ffly_height', label: 'Fly Height', type: 'number' as const, validation: mobSchema.shape.ffly_height },
  { key: 'sznametext', label: 'Display Name', type: 'text' as const, validation: mobSchema.shape.sznametext },
  { key: 'bspawn_animation', label: 'Spawn Animation', type: 'boolean' as const, validation: mobSchema.shape.bspawn_animation },
  { key: 'dwdialoggroup', label: 'Dialog Group', type: 'number' as const, validation: mobSchema.shape.dwdialoggroup },
  { key: 'szillust', label: 'Illustration', type: 'text' as const, validation: mobSchema.shape.szillust },
  { key: 'dwallianceidx', label: 'Alliance Index', type: 'number' as const, validation: mobSchema.shape.dwallianceidx },
  { key: 'waggromaxcount', label: 'Max Aggro Count', type: 'number' as const, validation: mobSchema.shape.waggromaxcount },
  { key: 'dwnpcattributeflag', label: 'NPC Attribute Flag', type: 'number' as const, validation: mobSchema.shape.dwnpcattributeflag },
  { key: 'wstomachachedefence', label: 'Stomachache Defense', type: 'number' as const, validation: mobSchema.shape.wstomachachedefence },
  { key: 'wpoisondefence', label: 'Poison Defense', type: 'number' as const, validation: mobSchema.shape.wpoisondefence },
  { key: 'wbleeddefence', label: 'Bleed Defense', type: 'number' as const, validation: mobSchema.shape.wbleeddefence },
  { key: 'wburndefence', label: 'Burn Defense', type: 'number' as const, validation: mobSchema.shape.wburndefence },
  { key: 'fscale', label: 'Scale', type: 'number' as const, validation: mobSchema.shape.fscale },
  { key: 'wattack_speed_rate', label: 'Attack Speed Rate', type: 'number' as const, validation: mobSchema.shape.wattack_speed_rate },
  { key: 'byattack_type', label: 'Attack Type', type: 'number' as const, validation: mobSchema.shape.byattack_type },
  { key: 'fattack_range', label: 'Attack Range', type: 'number' as const, validation: mobSchema.shape.fattack_range },
  { key: 'wattack_rate', label: 'Attack Rate', type: 'number' as const, validation: mobSchema.shape.wattack_rate },
  { key: 'wdodge_rate', label: 'Dodge Rate', type: 'number' as const, validation: mobSchema.shape.wdodge_rate },
  { key: 'wblock_rate', label: 'Block Rate', type: 'number' as const, validation: mobSchema.shape.wblock_rate },
  { key: 'wcurse_success_rate', label: 'Curse Success Rate', type: 'number' as const, validation: mobSchema.shape.wcurse_success_rate },
  { key: 'wcurse_tolerance_rate', label: 'Curse Tolerance Rate', type: 'number' as const, validation: mobSchema.shape.wcurse_tolerance_rate },
  { key: 'fradius', label: 'Radius', type: 'number' as const, validation: mobSchema.shape.fradius },
  { key: 'wbasic_aggro_point', label: 'Base Aggro Point', type: 'number' as const, validation: mobSchema.shape.wbasic_aggro_point },
  { key: 'dwmobgroup', label: 'Mob Group', type: 'number' as const, validation: mobSchema.shape.dwmobgroup },
  { key: 'wmob_kind', label: 'Mob Kind', type: 'number' as const, validation: mobSchema.shape.wmob_kind },
  { key: 'dwdrop_zenny', label: 'Drop Zenny', type: 'number' as const, validation: mobSchema.shape.dwdrop_zenny },
  { key: 'fdrop_zenny_rate', label: 'Drop Zenny Rate', type: 'number' as const, validation: mobSchema.shape.fdrop_zenny_rate },
  { key: 'dwexp', label: 'EXP', type: 'number' as const, validation: mobSchema.shape.dwexp },
  { key: 'bymob_type', label: 'Mob Type', type: 'number' as const, validation: mobSchema.shape.bymob_type },
  { key: 'drop_item_tblidx', label: 'Drop Item ID', type: 'number' as const, validation: mobSchema.shape.drop_item_tblidx },
  { key: 'bsize', label: 'Size', type: 'boolean' as const, validation: mobSchema.shape.bsize },
  { key: 'wtmqpoint', label: 'TMQ Point', type: 'number' as const, validation: mobSchema.shape.wtmqpoint },
  { key: 'dropquesttblidx', label: 'Drop Quest ID', type: 'number' as const, validation: mobSchema.shape.dropquesttblidx },
  { key: 'idxbigbag1', label: 'Big Bag 1', type: 'number' as const, validation: mobSchema.shape.idxbigbag1 },
  { key: 'bydroprate1', label: 'Drop Rate 1', type: 'number' as const, validation: mobSchema.shape.bydroprate1 },
  { key: 'bytrycount1', label: 'Try Count 1', type: 'number' as const, validation: mobSchema.shape.bytrycount1 },
  { key: 'idxbigbag2', label: 'Big Bag 2', type: 'number' as const, validation: mobSchema.shape.idxbigbag2 },
  { key: 'bydroprate2', label: 'Drop Rate 2', type: 'number' as const, validation: mobSchema.shape.bydroprate2 },
  { key: 'bytrycount2', label: 'Try Count 2', type: 'number' as const, validation: mobSchema.shape.bytrycount2 },
  { key: 'idxbigbag3', label: 'Big Bag 3', type: 'number' as const, validation: mobSchema.shape.idxbigbag3 },
  { key: 'bydroprate3', label: 'Drop Rate 3', type: 'number' as const, validation: mobSchema.shape.bydroprate3 },
  { key: 'bytrycount3', label: 'Try Count 3', type: 'number' as const, validation: mobSchema.shape.bytrycount3 },
  { key: 'dwunknown', label: 'Unknown', type: 'number' as const, validation: mobSchema.shape.dwunknown },
  { key: 'byunknown', label: 'Unknown', type: 'number' as const, validation: mobSchema.shape.byunknown },
  { key: 'byunknown2', label: 'Unknown 2', type: 'number' as const, validation: mobSchema.shape.byunknown2 },
  { key: 'bshow_name', label: 'Show Name', type: 'boolean' as const, validation: mobSchema.shape.bshow_name },
  { key: 'wsightangle', label: 'Sight Angle', type: 'number' as const, validation: mobSchema.shape.wsightangle },
  { key: 'dwimmunity_bit_flag', label: 'Immunity Bit Flag', type: 'number' as const, validation: mobSchema.shape.dwimmunity_bit_flag },
  { key: 'bisdragonballdrop', label: 'Is Dragon Ball Drop', type: 'boolean' as const, validation: mobSchema.shape.bisdragonballdrop },
  { key: 'wmonsterclass', label: 'Monster Class', type: 'number' as const, validation: mobSchema.shape.wmonsterclass },
  { key: 'wuserace', label: 'User Race', type: 'number' as const, validation: mobSchema.shape.wuserace },
  { key: 'frewardexprate', label: 'Reward EXP Rate', type: 'number' as const, validation: mobSchema.shape.frewardexprate },
  { key: 'frewardzennyrate', label: 'Reward Zenny Rate', type: 'number' as const, validation: mobSchema.shape.frewardzennyrate },
  { key: 'dwformulaoffset', label: 'Formula Offset', type: 'number' as const, validation: mobSchema.shape.dwformulaoffset },
  { key: 'fsettingrate_lp', label: 'Setting Rate LP', type: 'number' as const, validation: mobSchema.shape.fsettingrate_lp },
  { key: 'fsettingrate_lpregen', label: 'Setting Rate LP Regen', type: 'number' as const, validation: mobSchema.shape.fsettingrate_lpregen },
  { key: 'fsettingrate_phyoffence', label: 'Setting Rate Physical Offence', type: 'number' as const, validation: mobSchema.shape.fsettingrate_phyoffence },
  { key: 'fsettingrate_engoffence', label: 'Setting Rate Energy Offence', type: 'number' as const, validation: mobSchema.shape.fsettingrate_engoffence },
  { key: 'fsettingrate_phydefence', label: 'Setting Rate Physical Defence', type: 'number' as const, validation: mobSchema.shape.fsettingrate_phydefence },
  { key: 'fsettingrate_engdefence', label: 'Setting Rate Energy Defence', type: 'number' as const, validation: mobSchema.shape.fsettingrate_engdefence },
  { key: 'fsettingrate_attackrate', label: 'Setting Rate Attack Rate', type: 'number' as const, validation: mobSchema.shape.fsettingrate_attackrate },
  { key: 'fsettingrate_dodgerate', label: 'Setting Rate Dodge Rate', type: 'number' as const, validation: mobSchema.shape.fsettingrate_dodgerate },
  { key: 'fsettingphyoffencerate', label: 'Setting Physical Offence Rate', type: 'number' as const, validation: mobSchema.shape.fsettingphyoffencerate },
  { key: 'fsettingengoffencerate', label: 'Setting Energy Offence Rate', type: 'number' as const, validation: mobSchema.shape.fsettingengoffencerate },
  { key: 'fsettingrate_defence_role', label: 'Setting Rate Defence Role', type: 'number' as const, validation: mobSchema.shape.fsettingrate_defence_role },
  ...Array.from({ length: 7 }, (i) => [
    { key: `wuse_skill_time_${i}`, label: `Skill ${i} Time`, type: 'number' as const, validation: mobSchema.shape[`wuse_skill_time_${i}` as keyof typeof mobSchema.shape] },
    { key: `use_skill_tblidx_${i}`, label: `Skill ${i} Index`, type: 'number' as const, validation: mobSchema.shape[`use_skill_tblidx_${i}` as keyof typeof mobSchema.shape] },
    { key: `byuse_skill_basis_${i}`, label: `Skill ${i} Basis`, type: 'number' as const, validation: mobSchema.shape[`byuse_skill_basis_${i}` as keyof typeof mobSchema.shape] },
    { key: `wuse_skill_lp_${i}`, label: `Skill ${i} LP`, type: 'number' as const, validation: mobSchema.shape[`wuse_skill_lp_${i}` as keyof typeof mobSchema.shape] }
  ]).flat(),
]; 