import { z } from "zod";

export const worldSchema = z.object({
  table_id: z.string().uuid(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
  tblidx: z.number().nullable(),
szName: z.string().nullable().transform(e => e === null ? "" : e),
  wszName: z.string().nullable().transform(e => e === null ? "" : e),
  bDynamic: z.coerce.boolean().nullable(),
  nCreateCount: z.coerce.number().nullable(),
  dwDynamicCreateCountShareGroup: z.coerce.number().nullable(),
  byDoorType: z.coerce.number().nullable(),
  dwDestroyTimeInMilliSec: z.coerce.number().nullable(),
  wszMobSpawn_Table_Name: z.string().nullable().transform(e => e === null ? "" : e),
  wszNpcSpawn_Table_Name: z.string().nullable().transform(e => e === null ? "" : e),
  wszObjSpawn_Table_Name: z.string().nullable().transform(e => e === null ? "" : e),
  vStart_x: z.coerce.number().nullable(),
  vStart_y: z.coerce.number().nullable(),
  vStart_z: z.coerce.number().nullable(),
  vEnd_x: z.coerce.number().nullable(),
  vEnd_y: z.coerce.number().nullable(),
  vEnd_z: z.coerce.number().nullable(),
  vStandardLoc_x: z.coerce.number().nullable(),
  vStandardLoc_y: z.coerce.number().nullable(),
  vStandardLoc_z: z.coerce.number().nullable(),
  vBattleStartLoc_x: z.coerce.number().nullable(),
  vBattleStartLoc_y: z.coerce.number().nullable(),
  vBattleStartLoc_z: z.coerce.number().nullable(),
  vBattleEndLoc_x: z.coerce.number().nullable(),
  vBattleEndLoc_y: z.coerce.number().nullable(),
  vBattleEndLoc_z: z.coerce.number().nullable(),
  vBattleStart2Loc_x: z.coerce.number().nullable(),
  vBattleStart2Loc_y: z.coerce.number().nullable(),
  vBattleStart2Loc_z: z.coerce.number().nullable(),
  vBattleEnd2Loc_x: z.coerce.number().nullable(),
  vBattleEnd2Loc_y: z.coerce.number().nullable(),
  vBattleEnd2Loc_z: z.coerce.number().nullable(),
  vOutSideBattleStartLoc_x: z.coerce.number().nullable(),
  vOutSideBattleStartLoc_y: z.coerce.number().nullable(),
  vOutSideBattleStartLoc_z: z.coerce.number().nullable(),
  vOutSideBattleEndLoc_x: z.coerce.number().nullable(),
  vOutSideBattleEndLoc_y: z.coerce.number().nullable(),
  vOutSideBattleEndLoc_z: z.coerce.number().nullable(),
  vSpectatorStartLoc_x: z.coerce.number().nullable(),
  vSpectatorStartLoc_y: z.coerce.number().nullable(),
  vSpectatorStartLoc_z: z.coerce.number().nullable(),
  vSpectatorEndLoc_x: z.coerce.number().nullable(),
  vSpectatorEndLoc_y: z.coerce.number().nullable(),
  vSpectatorEndLoc_z: z.coerce.number().nullable(),
  vDefaultLoc_x: z.coerce.number().nullable(),
  vDefaultLoc_y: z.coerce.number().nullable(),
  vDefaultLoc_z: z.coerce.number().nullable(),
  vDefaultDir_x: z.coerce.number().nullable(),
  vDefaultDir_y: z.coerce.number().nullable(),
  vDefaultDir_z: z.coerce.number().nullable(),
  vStart1Loc_x: z.coerce.number().nullable(),
  vStart1Loc_y: z.coerce.number().nullable(),
  vStart1Loc_z: z.coerce.number().nullable(),
  vStart1Dir_x: z.coerce.number().nullable(),
  vStart1Dir_y: z.coerce.number().nullable(),
  vStart1Dir_z: z.coerce.number().nullable(),
  vStart2Loc_x: z.coerce.number().nullable(),
  vStart2Loc_y: z.coerce.number().nullable(),
  vStart2Loc_z: z.coerce.number().nullable(),
  vStart2Dir_x: z.coerce.number().nullable(),
  vStart2Dir_y: z.coerce.number().nullable(),
  vStart2Dir_z: z.coerce.number().nullable(),
  vWaitingPoint1Loc_x: z.coerce.number().nullable(),
  vWaitingPoint1Loc_y: z.coerce.number().nullable(),
  vWaitingPoint1Loc_z: z.coerce.number().nullable(),
  vWaitingPoint1Dir_x: z.coerce.number().nullable(),
  vWaitingPoint1Dir_y: z.coerce.number().nullable(),
  vWaitingPoint1Dir_z: z.coerce.number().nullable(),
  vWaitingPoint2Loc_x: z.coerce.number().nullable(),
  vWaitingPoint2Loc_y: z.coerce.number().nullable(),
  vWaitingPoint2Loc_z: z.coerce.number().nullable(),
  vWaitingPoint2Dir_x: z.coerce.number().nullable(),
  vWaitingPoint2Dir_y: z.coerce.number().nullable(),
  vWaitingPoint2Dir_z: z.coerce.number().nullable(),
  fSplitSize: z.coerce.number().nullable(),
  bNight_Able: z.coerce.boolean().nullable(),
  byStatic_Time: z.coerce.number().nullable(),
  wFuncFlag: z.coerce.number().nullable(),
  byWorldRuleType: z.coerce.number().nullable(),
  worldRuleTbldx: z.coerce.number().nullable(),
  outWorldTblidx: z.coerce.number().nullable(),
  outWorldLoc_x: z.coerce.number().nullable(),
  outWorldLoc_y: z.coerce.number().nullable(),
  outWorldLoc_z: z.coerce.number().nullable(),
  outWorldDir_x: z.coerce.number().nullable(),
  outWorldDir_y: z.coerce.number().nullable(),
  outWorldDir_z: z.coerce.number().nullable(),
  wszResourceFolder: z.string().nullable().transform(e => e === null ? "" : e),
  fBGMRestTime: z.coerce.number().nullable(),
  dwWorldResourceID: z.coerce.number().nullable(),
  fFreeCamera_Height: z.coerce.number().nullable(),
  wszEnterResourceFlash: z.string().nullable().transform(e => e === null ? "" : e),
  wszLeaveResourceFlash: z.string().nullable().transform(e => e === null ? "" : e),
  wpsLinkIndex: z.coerce.number().nullable(),
  byStartPointRange: z.coerce.number().nullable(),
  dwProhibition_Bit_Flag: z.coerce.number().nullable(),
  abyDragonBallHaveRate_0: z.coerce.number().nullable(),
  abyDragonBallDropRate_0: z.coerce.number().nullable(),
  abyDragonBallHaveRate_1: z.coerce.number().nullable(),
  abyDragonBallDropRate_1: z.coerce.number().nullable(),
  abyDragonBallHaveRate_2: z.coerce.number().nullable(),
  abyDragonBallDropRate_2: z.coerce.number().nullable(),
  abyDragonBallHaveRate_3: z.coerce.number().nullable(),
  abyDragonBallDropRate_3: z.coerce.number().nullable(),
  abyDragonBallHaveRate_4: z.coerce.number().nullable(),
  abyDragonBallDropRate_4: z.coerce.number().nullable(),
  abyDragonBallHaveRate_5: z.coerce.number().nullable(),
  abyDragonBallDropRate_5: z.coerce.number().nullable(),
  abyDragonBallHaveRate_6: z.coerce.number().nullable(),
  abyDragonBallDropRate_6: z.coerce.number().nullable(),
  abyDragonBallHaveRate_7: z.coerce.number().nullable(),
  abyDragonBallDropRate_7: z.coerce.number().nullable(),
  abyDragonBallHaveRate_8: z.coerce.number().nullable(),
  abyDragonBallDropRate_8: z.coerce.number().nullable(),
  abyDragonBallHaveRate_9: z.coerce.number().nullable(),
  abyDragonBallDropRate_9: z.coerce.number().nullable(),
});

export type WorldFormData = z.infer<typeof worldSchema> & { table_id: string };

// Helper to create coordinate columns
const createCoordColumns = (prefix: string, label: string) => [
  { key: `${prefix}_x`, label: `${label} X`, type: 'number' as const, validation: worldSchema.shape[`${prefix}_x` as keyof typeof worldSchema.shape] },
  { key: `${prefix}_y`, label: `${label} Y`, type: 'number' as const, validation: worldSchema.shape[`${prefix}_y` as keyof typeof worldSchema.shape] },
  { key: `${prefix}_z`, label: `${label} Z`, type: 'number' as const, validation: worldSchema.shape[`${prefix}_z` as keyof typeof worldSchema.shape] },
];

export const columns = [
  { key: 'tblidx', label: 'ID', type: 'number' as const, validation: worldSchema.shape.tblidx },
  { key: 'szName', label: 'Name', type: 'text' as const, validation: worldSchema.shape.szName },
  { key: 'wszName', label: 'Wide Name', type: 'text' as const, validation: worldSchema.shape.wszName },
  { key: 'bDynamic', label: 'Dynamic', type: 'boolean' as const, validation: worldSchema.shape.bDynamic },
  { key: 'nCreateCount', label: 'Create Count', type: 'number' as const, validation: worldSchema.shape.nCreateCount },
  { key: 'dwDynamicCreateCountShareGroup', label: 'Dynamic Create Count Share Group', type: 'number' as const, validation: worldSchema.shape.dwDynamicCreateCountShareGroup },
  { key: 'byDoorType', label: 'Door Type', type: 'number' as const, validation: worldSchema.shape.byDoorType },
  { key: 'dwDestroyTimeInMilliSec', label: 'Destroy Time (ms)', type: 'number' as const, validation: worldSchema.shape.dwDestroyTimeInMilliSec },
  { key: 'wszMobSpawn_Table_Name', label: 'Mob Spawn Table', type: 'text' as const, validation: worldSchema.shape.wszMobSpawn_Table_Name },
  { key: 'wszNpcSpawn_Table_Name', label: 'NPC Spawn Table', type: 'text' as const, validation: worldSchema.shape.wszNpcSpawn_Table_Name },
  { key: 'wszObjSpawn_Table_Name', label: 'Object Spawn Table', type: 'text' as const, validation: worldSchema.shape.wszObjSpawn_Table_Name },
  ...createCoordColumns('vStart', 'Start'),
  ...createCoordColumns('vEnd', 'End'),
  ...createCoordColumns('vStandardLoc', 'Standard Location'),
  ...createCoordColumns('vBattleStartLoc', 'Battle Start Location'),
  ...createCoordColumns('vBattleEndLoc', 'Battle End Location'),
  ...createCoordColumns('vBattleStart2Loc', 'Battle Start 2 Location'),
  ...createCoordColumns('vBattleEnd2Loc', 'Battle End 2 Location'),
  ...createCoordColumns('vOutSideBattleStartLoc', 'Outside Battle Start Location'),
  ...createCoordColumns('vOutSideBattleEndLoc', 'Outside Battle End Location'),
  ...createCoordColumns('vSpectatorStartLoc', 'Spectator Start Location'),
  ...createCoordColumns('vSpectatorEndLoc', 'Spectator End Location'),
  ...createCoordColumns('vDefaultLoc', 'Default Location'),
  ...createCoordColumns('vDefaultDir', 'Default Direction'),
  ...createCoordColumns('vStart1Loc', 'Start 1 Location'),
  ...createCoordColumns('vStart1Dir', 'Start 1 Direction'),
  ...createCoordColumns('vStart2Loc', 'Start 2 Location'),
  ...createCoordColumns('vStart2Dir', 'Start 2 Direction'),
  ...createCoordColumns('vWaitingPoint1Loc', 'Waiting Point 1 Location'),
  ...createCoordColumns('vWaitingPoint1Dir', 'Waiting Point 1 Direction'),
  ...createCoordColumns('vWaitingPoint2Loc', 'Waiting Point 2 Location'),
  ...createCoordColumns('vWaitingPoint2Dir', 'Waiting Point 2 Direction'),
  { key: 'fSplitSize', label: 'Split Size', type: 'number' as const, validation: worldSchema.shape.fSplitSize },
  { key: 'bNight_Able', label: 'Night Enabled', type: 'boolean' as const, validation: worldSchema.shape.bNight_Able },
  { key: 'byStatic_Time', label: 'Static Time', type: 'number' as const, validation: worldSchema.shape.byStatic_Time },
  { key: 'wFuncFlag', label: 'Function Flag', type: 'number' as const, validation: worldSchema.shape.wFuncFlag },
  { key: 'byWorldRuleType', label: 'World Rule Type', type: 'number' as const, validation: worldSchema.shape.byWorldRuleType },
  { key: 'worldRuleTbldx', label: 'World Rule Table ID', type: 'number' as const, validation: worldSchema.shape.worldRuleTbldx },
  { key: 'outWorldTblidx', label: 'Outworld Table ID', type: 'number' as const, validation: worldSchema.shape.outWorldTblidx },
  ...createCoordColumns('outWorldLoc', 'Outworld Location'),
  ...createCoordColumns('outWorldDir', 'Outworld Direction'),
  { key: 'wszResourceFolder', label: 'Resource Folder', type: 'text' as const, validation: worldSchema.shape.wszResourceFolder },
  { key: 'fBGMRestTime', label: 'BGM Rest Time', type: 'number' as const, validation: worldSchema.shape.fBGMRestTime },
  { key: 'dwWorldResourceID', label: 'World Resource ID', type: 'number' as const, validation: worldSchema.shape.dwWorldResourceID },
  { key: 'fFreeCamera_Height', label: 'Free Camera Height', type: 'number' as const, validation: worldSchema.shape.fFreeCamera_Height },
  { key: 'wszEnterResourceFlash', label: 'Enter Resource Flash', type: 'text' as const, validation: worldSchema.shape.wszEnterResourceFlash },
  { key: 'wszLeaveResourceFlash', label: 'Leave Resource Flash', type: 'text' as const, validation: worldSchema.shape.wszLeaveResourceFlash },
  { key: 'wpsLinkIndex', label: 'PS Link Index', type: 'number' as const, validation: worldSchema.shape.wpsLinkIndex },
  { key: 'byStartPointRange', label: 'Start Point Range', type: 'number' as const, validation: worldSchema.shape.byStartPointRange },
  { key: 'dwProhibition_Bit_Flag', label: 'Prohibition Bit Flag', type: 'number' as const, validation: worldSchema.shape.dwProhibition_Bit_Flag },
  ...Array.from({ length: 10 }, (_, i) => [
    { key: `abyDragonBallHaveRate_${i}`, label: `Dragon Ball Have Rate ${i}`, type: 'number' as const, validation: worldSchema.shape[`abyDragonBallHaveRate_${i}` as keyof typeof worldSchema.shape] },
    { key: `abyDragonBallDropRate_${i}`, label: `Dragon Ball Drop Rate ${i}`, type: 'number' as const, validation: worldSchema.shape[`abyDragonBallDropRate_${i}` as keyof typeof worldSchema.shape] }
  ]).flat(),
];
