import { z } from "zod";

export const worldSchema = z.object({
  tblidx: z.number().nullable(),
  szname: z.string().nullable(),
  wszname: z.string().nullable(),
  bdynamic: z.boolean().nullable(),
  ncreatecount: z.number().nullable(),
  dwdynamiccreatecountsharegroup: z.number().nullable(),
  bydoortype: z.number().nullable(),
  dwdestroytimeinmillisec: z.number().nullable(),
  wszmobspawn_table_name: z.string().nullable(),
  wsznpcspawn_table_name: z.string().nullable(),
  wszobjspawn_table_name: z.string().nullable(),
  // Location coordinates
  vstart_x: z.number().nullable(),
  vstart_y: z.number().nullable(),
  vstart_z: z.number().nullable(),
  vend_x: z.number().nullable(),
  vend_y: z.number().nullable(),
  vend_z: z.number().nullable(),
  vstandardloc_x: z.number().nullable(),
  vstandardloc_y: z.number().nullable(),
  vstandardloc_z: z.number().nullable(),
  // Battle locations
  vbattlestartloc_x: z.number().nullable(),
  vbattlestartloc_y: z.number().nullable(),
  vbattlestartloc_z: z.number().nullable(),
  vbattleendloc_x: z.number().nullable(),
  vbattleendloc_y: z.number().nullable(),
  vbattleendloc_z: z.number().nullable(),
  vbattlestart2loc_x: z.number().nullable(),
  vbattlestart2loc_y: z.number().nullable(),
  vbattlestart2loc_z: z.number().nullable(),
  vbattleend2loc_x: z.number().nullable(),
  vbattleend2loc_y: z.number().nullable(),
  vbattleend2loc_z: z.number().nullable(),
  // Outside battle locations
  voutsidebattlestartloc_x: z.number().nullable(),
  voutsidebattlestartloc_y: z.number().nullable(),
  voutsidebattlestartloc_z: z.number().nullable(),
  voutsidebattleendloc_x: z.number().nullable(),
  voutsidebattleendloc_y: z.number().nullable(),
  voutsidebattleendloc_z: z.number().nullable(),
  // Spectator locations
  vspectatorstartloc_x: z.number().nullable(),
  vspectatorstartloc_y: z.number().nullable(),
  vspectatorstartloc_z: z.number().nullable(),
  vspectatorendloc_x: z.number().nullable(),
  vspectatorendloc_y: z.number().nullable(),
  vspectatorendloc_z: z.number().nullable(),
  // Default locations and directions
  vdefaultloc_x: z.number().nullable(),
  vdefaultloc_y: z.number().nullable(),
  vdefaultloc_z: z.number().nullable(),
  vdefaultdir_x: z.number().nullable(),
  vdefaultdir_y: z.number().nullable(),
  vdefaultdir_z: z.number().nullable(),
  // Start locations and directions
  vstart1loc_x: z.number().nullable(),
  vstart1loc_y: z.number().nullable(),
  vstart1loc_z: z.number().nullable(),
  vstart1dir_x: z.number().nullable(),
  vstart1dir_y: z.number().nullable(),
  vstart1dir_z: z.number().nullable(),
  vstart2loc_x: z.number().nullable(),
  vstart2loc_y: z.number().nullable(),
  vstart2loc_z: z.number().nullable(),
  vstart2dir_x: z.number().nullable(),
  vstart2dir_y: z.number().nullable(),
  vstart2dir_z: z.number().nullable(),
  // Waiting point locations and directions
  vwaitingpoint1loc_x: z.number().nullable(),
  vwaitingpoint1loc_y: z.number().nullable(),
  vwaitingpoint1loc_z: z.number().nullable(),
  vwaitingpoint1dir_x: z.number().nullable(),
  vwaitingpoint1dir_y: z.number().nullable(),
  vwaitingpoint1dir_z: z.number().nullable(),
  vwaitingpoint2loc_x: z.number().nullable(),
  vwaitingpoint2loc_y: z.number().nullable(),
  vwaitingpoint2loc_z: z.number().nullable(),
  vwaitingpoint2dir_x: z.number().nullable(),
  vwaitingpoint2dir_y: z.number().nullable(),
  vwaitingpoint2dir_z: z.number().nullable(),
  // World settings
  fsplitsize: z.number().nullable(),
  bnight_able: z.boolean().nullable(),
  bystatic_time: z.number().nullable(),
  wfuncflag: z.number().nullable(),
  byworldruletype: z.number().nullable(),
  worldruletbldx: z.number().nullable(),
  // Outworld settings
  outworldtblidx: z.number().nullable(),
  outworldloc_x: z.number().nullable(),
  outworldloc_y: z.number().nullable(),
  outworldloc_z: z.number().nullable(),
  outworlddir_x: z.number().nullable(),
  outworlddir_y: z.number().nullable(),
  outworlddir_z: z.number().nullable(),
  // Resource settings
  wszresourcefolder: z.string().nullable(),
  fbgmresttime: z.number().nullable(),
  dwworldresourceid: z.number().nullable(),
  ffreecamera_height: z.number().nullable(),
  wszenterresourceflash: z.string().nullable(),
  wszleaveresourceflash: z.string().nullable(),
  // Additional settings
  wpslinkindex: z.number().nullable(),
  bystartpointrange: z.number().nullable(),
  dwprohibition_bit_flag: z.number().nullable(),
  // Dragon ball rates
  abydragonballhaverate_0: z.number().nullable(),
  abydragonballdroprate_0: z.number().nullable(),
  abydragonballhaverate_1: z.number().nullable(),
  abydragonballdroprate_1: z.number().nullable(),
  abydragonballhaverate_2: z.number().nullable(),
  abydragonballdroprate_2: z.number().nullable(),
  abydragonballhaverate_3: z.number().nullable(),
  abydragonballdroprate_3: z.number().nullable(),
  abydragonballhaverate_4: z.number().nullable(),
  abydragonballdroprate_4: z.number().nullable(),
}); 