import { z } from "zod";

export const worldSchema = z.object({
  table_id: z.string().uuid(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
  tblidx: z.number().nullable(),
  szname: z.string().nullable(),
  wszname: z.string().nullable(),
  bdynamic: z.boolean().nullable(),
  ncreatecount: z.number().nullable(),
  dwdynamiccreatecountsharegroup: z.number().nullable(),
  bydoortype: z.number().nullable(),
  dwdestroytimeinmillisec: z.number().nullable(),
  wszmobspawn_table_name: z.string().nullable(),
  wsznpcspawn_table_name: z.string().nullable(),
  wszobjspawn_table_name: z.string().nullable(),
  // Location coordinates
  vstart_x: z.number().nullable(),
  vstart_y: z.number().nullable(),
  vstart_z: z.number().nullable(),
  vend_x: z.number().nullable(),
  vend_y: z.number().nullable(),
  vend_z: z.number().nullable(),
  vstandardloc_x: z.number().nullable(),
  vstandardloc_y: z.number().nullable(),
  vstandardloc_z: z.number().nullable(),
  // Battle locations
  vbattlestartloc_x: z.number().nullable(),
  vbattlestartloc_y: z.number().nullable(),
  vbattlestartloc_z: z.number().nullable(),
  vbattleendloc_x: z.number().nullable(),
  vbattleendloc_y: z.number().nullable(),
  vbattleendloc_z: z.number().nullable(),
  vbattlestart2loc_x: z.number().nullable(),
  vbattlestart2loc_y: z.number().nullable(),
  vbattlestart2loc_z: z.number().nullable(),
  vbattleend2loc_x: z.number().nullable(),
  vbattleend2loc_y: z.number().nullable(),
  vbattleend2loc_z: z.number().nullable(),
  // Outside battle locations
  voutsidebattlestartloc_x: z.number().nullable(),
  voutsidebattlestartloc_y: z.number().nullable(),
  voutsidebattlestartloc_z: z.number().nullable(),
  voutsidebattleendloc_x: z.number().nullable(),
  voutsidebattleendloc_y: z.number().nullable(),
  voutsidebattleendloc_z: z.number().nullable(),
  // Spectator locations
  vspectatorstartloc_x: z.number().nullable(),
  vspectatorstartloc_y: z.number().nullable(),
  vspectatorstartloc_z: z.number().nullable(),
  vspectatorendloc_x: z.number().nullable(),
  vspectatorendloc_y: z.number().nullable(),
  vspectatorendloc_z: z.number().nullable(),
  // Default locations and directions
  vdefaultloc_x: z.number().nullable(),
  vdefaultloc_y: z.number().nullable(),
  vdefaultloc_z: z.number().nullable(),
  vdefaultdir_x: z.number().nullable(),
  vdefaultdir_y: z.number().nullable(),
  vdefaultdir_z: z.number().nullable(),
  // Start locations and directions
  vstart1loc_x: z.number().nullable(),
  vstart1loc_y: z.number().nullable(),
  vstart1loc_z: z.number().nullable(),
  vstart1dir_x: z.number().nullable(),
  vstart1dir_y: z.number().nullable(),
  vstart1dir_z: z.number().nullable(),
  vstart2loc_x: z.number().nullable(),
  vstart2loc_y: z.number().nullable(),
  vstart2loc_z: z.number().nullable(),
  vstart2dir_x: z.number().nullable(),
  vstart2dir_y: z.number().nullable(),
  vstart2dir_z: z.number().nullable(),
  // Waiting point locations and directions
  vwaitingpoint1loc_x: z.number().nullable(),
  vwaitingpoint1loc_y: z.number().nullable(),
  vwaitingpoint1loc_z: z.number().nullable(),
  vwaitingpoint1dir_x: z.number().nullable(),
  vwaitingpoint1dir_y: z.number().nullable(),
  vwaitingpoint1dir_z: z.number().nullable(),
  vwaitingpoint2loc_x: z.number().nullable(),
  vwaitingpoint2loc_y: z.number().nullable(),
  vwaitingpoint2loc_z: z.number().nullable(),
  vwaitingpoint2dir_x: z.number().nullable(),
  vwaitingpoint2dir_y: z.number().nullable(),
  vwaitingpoint2dir_z: z.number().nullable(),
  // World settings
  fsplitsize: z.number().nullable(),
  bnight_able: z.boolean().nullable(),
  bystatic_time: z.number().nullable(),
  wfuncflag: z.number().nullable(),
  byworldruletype: z.number().nullable(),
  worldruletbldx: z.number().nullable(),
  // Outworld settings
  outworldtblidx: z.number().nullable(),
  outworldloc_x: z.number().nullable(),
  outworldloc_y: z.number().nullable(),
  outworldloc_z: z.number().nullable(),
  outworlddir_x: z.number().nullable(),
  outworlddir_y: z.number().nullable(),
  outworlddir_z: z.number().nullable(),
  // Resource settings
  wszresourcefolder: z.string().nullable(),
  fbgmresttime: z.number().nullable(),
  dwworldresourceid: z.number().nullable(),
  ffreecamera_height: z.number().nullable(),
  wszenterresourceflash: z.string().nullable(),
  wszleaveresourceflash: z.string().nullable(),
  // Additional settings
  wpslinkindex: z.number().nullable(),
  bystartpointrange: z.number().nullable(),
  dwprohibition_bit_flag: z.number().nullable(),
  // Dragon ball rates
  abydragonballhaverate_0: z.number().nullable(),
  abydragonballdroprate_0: z.number().nullable(),
  abydragonballhaverate_1: z.number().nullable(),
  abydragonballdroprate_1: z.number().nullable(),
  abydragonballhaverate_2: z.number().nullable(),
  abydragonballdroprate_2: z.number().nullable(),
  abydragonballhaverate_3: z.number().nullable(),
  abydragonballdroprate_3: z.number().nullable(),
  abydragonballhaverate_4: z.number().nullable(),
  abydragonballdroprate_4: z.number().nullable(),
});

export type WorldFormData = z.infer<typeof worldSchema> & { table_id: string };

// Helper to create coordinate columns
const createCoordColumns = (prefix: string, label: string) => [
  { key: `${prefix}_x`, label: `${label} X`, type: 'number' as const, validation: worldSchema.shape[`${prefix}_x` as keyof typeof worldSchema.shape] },
  { key: `${prefix}_y`, label: `${label} Y`, type: 'number' as const, validation: worldSchema.shape[`${prefix}_y` as keyof typeof worldSchema.shape] },
  { key: `${prefix}_z`, label: `${label} Z`, type: 'number' as const, validation: worldSchema.shape[`${prefix}_z` as keyof typeof worldSchema.shape] },
];

export const columns = [
  { key: 'tblidx', label: 'ID', type: 'number' as const, validation: worldSchema.shape.tblidx },
  { key: 'szname', label: 'Name', type: 'text' as const, validation: worldSchema.shape.szname },
  { key: 'wszname', label: 'Wide Name', type: 'text' as const, validation: worldSchema.shape.wszname },
  { key: 'bdynamic', label: 'Dynamic', type: 'boolean' as const, validation: worldSchema.shape.bdynamic },
  { key: 'ncreatecount', label: 'Create Count', type: 'number' as const, validation: worldSchema.shape.ncreatecount },
  { key: 'dwdynamiccreatecountsharegroup', label: 'Dynamic Create Count Share Group', type: 'number' as const, validation: worldSchema.shape.dwdynamiccreatecountsharegroup },
  { key: 'bydoortype', label: 'Door Type', type: 'number' as const, validation: worldSchema.shape.bydoortype },
  { key: 'dwdestroytimeinmillisec', label: 'Destroy Time (ms)', type: 'number' as const, validation: worldSchema.shape.dwdestroytimeinmillisec },
  { key: 'wszmobspawn_table_name', label: 'Mob Spawn Table', type: 'text' as const, validation: worldSchema.shape.wszmobspawn_table_name },
  { key: 'wsznpcspawn_table_name', label: 'NPC Spawn Table', type: 'text' as const, validation: worldSchema.shape.wsznpcspawn_table_name },
  { key: 'wszobjspawn_table_name', label: 'Object Spawn Table', type: 'text' as const, validation: worldSchema.shape.wszobjspawn_table_name },
  ...createCoordColumns('vstart', 'Start'),
  ...createCoordColumns('vend', 'End'),
  ...createCoordColumns('vstandardloc', 'Standard Location'),
  ...createCoordColumns('vbattlestartloc', 'Battle Start Location'),
  ...createCoordColumns('vbattleendloc', 'Battle End Location'),
  ...createCoordColumns('vbattlestart2loc', 'Battle Start 2 Location'),
  ...createCoordColumns('vbattleend2loc', 'Battle End 2 Location'),
  ...createCoordColumns('voutsidebattlestartloc', 'Outside Battle Start Location'),
  ...createCoordColumns('voutsidebattleendloc', 'Outside Battle End Location'),
  ...createCoordColumns('vspectatorstartloc', 'Spectator Start Location'),
  ...createCoordColumns('vspectatorendloc', 'Spectator End Location'),
  ...createCoordColumns('vdefaultloc', 'Default Location'),
  ...createCoordColumns('vdefaultdir', 'Default Direction'),
  ...createCoordColumns('vstart1loc', 'Start 1 Location'),
  ...createCoordColumns('vstart1dir', 'Start 1 Direction'),
  ...createCoordColumns('vstart2loc', 'Start 2 Location'),
  ...createCoordColumns('vstart2dir', 'Start 2 Direction'),
  ...createCoordColumns('vwaitingpoint1loc', 'Waiting Point 1 Location'),
  ...createCoordColumns('vwaitingpoint1dir', 'Waiting Point 1 Direction'),
  ...createCoordColumns('vwaitingpoint2loc', 'Waiting Point 2 Location'),
  ...createCoordColumns('vwaitingpoint2dir', 'Waiting Point 2 Direction'),
  { key: 'fsplitsize', label: 'Split Size', type: 'number' as const, validation: worldSchema.shape.fsplitsize },
  { key: 'bnight_able', label: 'Night Enabled', type: 'boolean' as const, validation: worldSchema.shape.bnight_able },
  { key: 'bystatic_time', label: 'Static Time', type: 'number' as const, validation: worldSchema.shape.bystatic_time },
  { key: 'wfuncflag', label: 'Function Flag', type: 'number' as const, validation: worldSchema.shape.wfuncflag },
  { key: 'byworldruletype', label: 'World Rule Type', type: 'number' as const, validation: worldSchema.shape.byworldruletype },
  { key: 'worldruletbldx', label: 'World Rule Table ID', type: 'number' as const, validation: worldSchema.shape.worldruletbldx },
  { key: 'outworldtblidx', label: 'Outworld Table ID', type: 'number' as const, validation: worldSchema.shape.outworldtblidx },
  ...createCoordColumns('outworldloc', 'Outworld Location'),
  ...createCoordColumns('outworlddir', 'Outworld Direction'),
  { key: 'wszresourcefolder', label: 'Resource Folder', type: 'text' as const, validation: worldSchema.shape.wszresourcefolder },
  { key: 'fbgmresttime', label: 'BGM Rest Time', type: 'number' as const, validation: worldSchema.shape.fbgmresttime },
  { key: 'dwworldresourceid', label: 'World Resource ID', type: 'number' as const, validation: worldSchema.shape.dwworldresourceid },
  { key: 'ffreecamera_height', label: 'Free Camera Height', type: 'number' as const, validation: worldSchema.shape.ffreecamera_height },
  { key: 'wszenterresourceflash', label: 'Enter Resource Flash', type: 'text' as const, validation: worldSchema.shape.wszenterresourceflash },
  { key: 'wszleaveresourceflash', label: 'Leave Resource Flash', type: 'text' as const, validation: worldSchema.shape.wszleaveresourceflash },
  { key: 'wpslinkindex', label: 'PS Link Index', type: 'number' as const, validation: worldSchema.shape.wpslinkindex },
  { key: 'bystartpointrange', label: 'Start Point Range', type: 'number' as const, validation: worldSchema.shape.bystartpointrange },
  { key: 'dwprohibition_bit_flag', label: 'Prohibition Bit Flag', type: 'number' as const, validation: worldSchema.shape.dwprohibition_bit_flag },
  ...Array.from({ length: 5 }, (_, i) => [
    { key: `abydragonballhaverate_${i}`, label: `Dragon Ball Have Rate ${i}`, type: 'number' as const, validation: worldSchema.shape[`abydragonballhaverate_${i}` as keyof typeof worldSchema.shape] },
    { key: `abydragonballdroprate_${i}`, label: `Dragon Ball Drop Rate ${i}`, type: 'number' as const, validation: worldSchema.shape[`abydragonballdroprate_${i}` as keyof typeof worldSchema.shape] }
  ]).flat(),
]; 